<?php
require_once __DIR__.'/../Core/DB.php';
require_once __DIR__.'/../../vendor/autoload.php';
use PhpOffice\PhpSpreadsheet\Spreadsheet;use PhpOffice\PhpSpreadsheet\Writer\Xlsx;use PhpOffice\PhpSpreadsheet\Style\Alignment;use PhpOffice\PhpSpreadsheet\Style\Border;

class AnggaranDocumentService
{
    private DB $db; private array $user; private ?string $currentSubCode=null;
    private const TABLES=['rkpd'=>'rkpd_neo','renja'=>'renja_neo','rka'=>'rka_neo','dpa'=>'dpa_neo','rkpd_p'=>'rkpd_p_neo','renja_p'=>'renja_p_neo','rka_p'=>'rka_p_neo','dppa'=>'dppa_neo'];
    public function __construct(array $user){$this->db=DB::getInstance();$this->user=$user;}
    private function table(string $logical):string{if(!isset(self::TABLES[$logical]))throw new InvalidArgumentException('Dokumen anggaran tidak valid');return self::TABLES[$logical];}
    private function scope(string $alias='a'):array{$w=$this->user['kd_wilayah']??'';$o=$this->user['kd_opd']??'';$y=(int)($this->user['tahun']??0);if(!$w||!$y)throw new RuntimeException('Scope pengguna tidak lengkap');$sql="$alias.kd_wilayah=? AND $alias.tahun=? AND $alias.is_deleted=0";$p=[$w,$y];if($o&&$o!=='0'){$sql.=" AND $alias.kd_opd=?";$p[]=$o;}return[$sql,$p];}
    public function groups(string $logical):array
    {
        $table=$this->table($logical);[$scope,$params]=$this->scope();$amount=str_starts_with($logical,'rkpd')?'a.pagu':'a.jumlah';$description=str_starts_with($logical,'rkpd')?'MAX(a.indikator)':'MAX(a.uraian)';
        $prefix="CONVERT(a.kd_sub_keg USING utf8mb4) COLLATE utf8mb4_general_ci";
        return $this->db->query("SELECT a.kd_sub_keg,COALESCE(r.uraian,$description) nama_sub_kegiatan,COUNT(*) jumlah_uraian,COALESCE(SUM($amount),0) total,MAX(a.setujui) setujui,MAX(a.kunci) kunci,
          (SELECT CONCAT(x.kode,' ',x.uraian) FROM rekening_kegiatan x WHERE x.level='program' AND $prefix LIKE CONCAT(x.kode,'.%') COLLATE utf8mb4_general_ci ORDER BY CHAR_LENGTH(x.kode) DESC LIMIT 1) program,
          (SELECT CONCAT(x.kode,' ',x.uraian) FROM rekening_kegiatan x WHERE x.level='kegiatan' AND $prefix LIKE CONCAT(x.kode,'.%') COLLATE utf8mb4_general_ci ORDER BY CHAR_LENGTH(x.kode) DESC LIMIT 1) kegiatan,
          (SELECT CONCAT(x.kode,' ',x.uraian) FROM rekening_kegiatan x WHERE x.level='bidang' AND $prefix LIKE CONCAT(x.kode,'.%') COLLATE utf8mb4_general_ci ORDER BY CHAR_LENGTH(x.kode) DESC LIMIT 1) bidang
          FROM `$table` a LEFT JOIN rekening_kegiatan r ON r.kode=$prefix AND r.level='sub_kegiatan' WHERE $scope GROUP BY a.kd_sub_keg,r.uraian ORDER BY a.kd_sub_keg",$params)->fetchAll();
    }
    public function details(string $logical,string $code):array
    {
        $table=$this->table($logical);[$scope,$params]=$this->scope();$params[]=$code;
        if(str_starts_with($logical,'rkpd'))$select='a.id,a.kd_sub_keg,a.indikator AS uraian,a.target AS volume,a.pagu AS jumlah,a.lokasi,a.kelompok_sasaran,a.kunci,a.setujui,a.keterangan';
        else {$columns=array_column($this->db->query("SHOW COLUMNS FROM `$table`")->fetchAll(),'Field');$awal=in_array('jumlah_awal',$columns,true)?'a.volume_awal,a.harga_satuan_awal,a.jumlah_awal,':'NULL volume_awal,NULL harga_satuan_awal,NULL jumlah_awal,';$select="a.id,a.kd_sub_keg,a.kd_akun,a.kel_rek,a.jenis_kelompok,a.kelompok,a.komponen,a.spesifikasi,a.uraian,a.volume,a.sat_1,a.harga_satuan,a.jumlah,$awal a.sumber_dana_id,a.kunci,a.setujui,a.keterangan";}
        $rows=$this->db->query("SELECT $select FROM `$table` a WHERE $scope AND a.kd_sub_keg=? ORDER BY a.kd_akun,a.id",$params)->fetchAll();foreach($rows as &$row)$row['akun_hierarchy']=$this->accountHierarchy((string)($row['kd_akun']??''));unset($row);return$rows;
    }

    private function isChange(string $logical):bool{return in_array($logical,['rkpd_p','renja_p','rka_p','dppa'],true);}
    private function documentLabel(string $logical):string{return match($logical){'renja'=>'RENJA','rka'=>'RKA','dpa'=>'DPA','renja_p'=>'RENJA PERUBAHAN','rka_p'=>'RKA PERUBAHAN','dppa'=>'DPPA',default=>strtoupper($logical)};}
    private function e(mixed $value):string{return htmlspecialchars((string)$value,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}
    private function money(mixed $value):string{return number_format((float)$value,2,',','.');}
    private function accountHierarchy(string $code):array
    {
        $parts=array_values(array_filter(explode('.',$code),fn($v)=>$v!==''));$prefixes=[];$current='';foreach($parts as $part){$current=$current===''?$part:$current.'.'.$part;$prefixes[]=$current;}if(!$prefixes)return[];
        $holders=implode(',',array_fill(0,count($prefixes),'?'));$rows=$this->db->query("SELECT kode,uraian FROM akun_neo WHERE kode IN ($holders) AND is_deleted=0 ORDER BY CHAR_LENGTH(kode),kode",$prefixes)->fetchAll();$map=[];foreach($rows as $r)$map[$r['kode']]=$r['uraian'];$out=[];foreach($prefixes as $prefix)$out[]=['kode'=>$prefix,'uraian'=>$map[$prefix]??('Rekening '.$prefix)];return$out;
    }
    private function hierarchyHtml(string $code,int $columns):string
    {
        $html='';foreach($this->accountHierarchy($code) as $depth=>$node){$html.='<tr style="background-color:'.($depth<2?'#d9eaf7':'#eef5fa').';font-weight:bold"><td>'.$this->e($node['kode']).'</td><td>'.$this->e($node['uraian']).'</td><td colspan="'.($columns-2).'"></td></tr>';}return$html;
    }
    private function metadataRows(array $group):string
    {
        $opd=$this->user['nama_opd']??$this->user['opd']??$this->user['kd_opd']??'-';$year=(int)($this->user['tahun']??0);
        $rows=[['Urusan Pemerintahan',$group['bidang']??'-'],['Program',$group['program']??'-'],['Kegiatan',$group['kegiatan']??'-'],['Organisasi',$opd],['Sub Kegiatan',($group['kd_sub_keg']??'').' '.($group['nama_sub_kegiatan']??'')],['Tahun Anggaran',(string)$year]];
        $html='';foreach($rows as [$label,$value])$html.='<tr><td width="23%"><b>'.$this->e($label).'</b></td><td width="2%">:</td><td width="75%">'.$this->e($value).'</td></tr>';return $html;
    }

    public function monthlyPlan(string $logical,int $anggaranId):array
    {
        if(!in_array($logical,['dpa','dppa'],true))throw new InvalidArgumentException('Rencana bulanan hanya untuk DPA/DPPA');$table=$this->table($logical);[$scope,$p]=$this->scope('a');$p[]=$anggaranId;
        $item=$this->db->query("SELECT a.id,a.kd_sub_keg,a.kd_akun,a.jumlah FROM `$table` a WHERE $scope AND a.id=?",$p)->fetch();if(!$item)throw new RuntimeException('Rincian anggaran tidak ditemukan');
        $rows=$this->db->query('SELECT bulan,nilai FROM rencana_realisasi_anggaran_neo WHERE dokumen=? AND anggaran_id=? AND is_deleted=0 ORDER BY bulan',[$logical,$anggaranId])->fetchAll();$months=array_fill(1,12,0.0);foreach($rows as $r)$months[(int)$r['bulan']]=(float)$r['nilai'];return ['item'=>$item,'months'=>$months,'total'=>array_sum($months)];
    }
    public function saveMonthlyPlan(string $logical,int $anggaranId,array $months):array
    {
        $plan=$this->monthlyPlan($logical,$anggaranId);$values=[];for($m=1;$m<=12;$m++){$v=(float)($months[$m]??$months[(string)$m]??0);if($v<0)throw new InvalidArgumentException('Nilai rencana bulanan tidak boleh negatif');$values[$m]=$v;}if(array_sum($values)>(float)$plan['item']['jumlah']+0.01)throw new InvalidArgumentException('Total rencana bulanan melebihi pagu rincian');$u=$this->user['username']??'system';$this->db->begin();try{foreach($values as $m=>$v)$this->db->query('INSERT INTO rencana_realisasi_anggaran_neo(dokumen,anggaran_id,kd_wilayah,kd_opd,tahun,kd_sub_keg,kd_akun,jenis,bulan,nilai,username_insert,is_deleted) VALUES(?,?,?,?,?,?,?,?,?,?,?,0) ON DUPLICATE KEY UPDATE nilai=VALUES(nilai),tgl_update=NOW(),username_update=VALUES(username_insert),is_deleted=0',[$logical,$anggaranId,$this->user['kd_wilayah'],$this->user['kd_opd'],$this->user['tahun'],$plan['item']['kd_sub_keg'],$plan['item']['kd_akun'],'belanja',$m,$v,$u]);$this->db->commit();}catch(Throwable $e){$this->db->rollback();throw $e;}return $this->monthlyPlan($logical,$anggaranId);
    }

    public function accountMonthlyRows(string $logical,string $subCode):array
    {
        if(!in_array($logical,['dpa','dppa'],true))throw new InvalidArgumentException('Rencana rekening hanya untuk DPA/DPPA');
        $table=$this->table($logical);[$scope,$params]=$this->scope('a');$params[]=$subCode;
        $rows=$this->db->query("SELECT a.kd_akun,MAX(COALESCE(k.uraian,a.kd_akun)) uraian,SUM(a.jumlah) pagu,COUNT(*) jumlah_uraian FROM `$table` a LEFT JOIN akun_neo k ON k.kode=a.kd_akun AND k.is_deleted=0 WHERE $scope AND a.kd_sub_keg=? AND a.kd_akun IS NOT NULL AND a.kd_akun<>'' GROUP BY a.kd_akun ORDER BY a.kd_akun",$params)->fetchAll();
        foreach($rows as &$row){$plan=$this->db->query('SELECT bulan,nilai FROM rencana_rekening_anggaran_neo WHERE dokumen=? AND kd_wilayah=? AND kd_opd=? AND tahun=? AND kd_sub_keg=? AND kd_akun=? AND jenis=? AND is_deleted=0 ORDER BY bulan',[$logical,$this->user['kd_wilayah'],$this->user['kd_opd'],$this->user['tahun'],$subCode,$row['kd_akun'],'belanja'])->fetchAll();$months=array_fill(1,12,0.0);foreach($plan as $value)$months[(int)$value['bulan']]=(float)$value['nilai'];$row['pagu']=(float)$row['pagu'];$row['months']=$months;$row['total_rencana']=array_sum($months);$row['sisa']=$row['pagu']-$row['total_rencana'];}unset($row);return$rows;
    }

    public function saveAccountMonthly(string $logical,string $subCode,string $account,array $months,string $kind='belanja'):array
    {
        if($kind!=='belanja')throw new InvalidArgumentException('Rencana pendapatan akan mengikuti rekening pendapatan pada DPA Pendapatan; rincian ini adalah rekening belanja');
        $rows=$this->accountMonthlyRows($logical,$subCode);$target=null;foreach($rows as $row)if($row['kd_akun']===$account){$target=$row;break;}if(!$target)throw new RuntimeException('Kode rekening level akhir tidak ditemukan pada sub kegiatan');
        $values=[];for($month=1;$month<=12;$month++){$value=(float)($months[$month]??$months[(string)$month]??0);if($value<0)throw new InvalidArgumentException('Nilai bulanan tidak boleh negatif');$values[$month]=$value;}if(array_sum($values)>$target['pagu']+0.01)throw new InvalidArgumentException('Total pembagian bulanan melebihi pagu rekening Rp '.number_format($target['pagu'],0,',','.'));
        $this->db->begin();try{foreach($values as $month=>$value)$this->db->query('INSERT INTO rencana_rekening_anggaran_neo(dokumen,kd_wilayah,kd_opd,tahun,kd_sub_keg,kd_akun,jenis,bulan,nilai,username_insert,is_deleted) VALUES(?,?,?,?,?,?,?,?,?,?,0) ON DUPLICATE KEY UPDATE nilai=VALUES(nilai),tgl_update=NOW(),username_update=VALUES(username_insert),is_deleted=0',[$logical,$this->user['kd_wilayah'],$this->user['kd_opd'],$this->user['tahun'],$subCode,$account,$kind,$month,$value,$this->user['username']??'system']);$this->db->commit();}catch(Throwable $e){$this->db->rollback();throw$e;}return$this->accountMonthlyRows($logical,$subCode);
    }
    public function activeTapd(?string $date=null):array
    {
        $date=$date?:date('Y-m-d');return $this->db->query('SELECT nama,nip,jabatan,urutan FROM tapd_penugasan_neo WHERE kd_wilayah=? AND tahun=? AND aktif=1 AND is_deleted=0 AND tanggal_mulai<=? AND tanggal_selesai>=? ORDER BY urutan,nama',[$this->user['kd_wilayah'],$this->user['tahun'],$date,$date])->fetchAll();
    }
    public function recapRows(string $logical):array
    {
        if(!in_array($logical,['dpa','dppa'],true))throw new InvalidArgumentException('Rekap hanya untuk DPA/DPPA');$table=$this->table($logical);[$scope,$p]=$this->scope('a');$change=$logical==='dppa';$before=$change?'COALESCE(SUM(a.jumlah_awal),0)':'0';return $this->db->query("SELECT a.kd_sub_keg,MAX(a.uraian) uraian,COALESCE(a.kd_akun,'-') kd_akun,$before sebelum,COALESCE(SUM(a.jumlah),0) sesudah,COALESCE(SUM(CASE WHEN a.kd_akun LIKE '5.1%' THEN a.jumlah ELSE 0 END),0) operasi,COALESCE(SUM(CASE WHEN a.kd_akun LIKE '5.2%' THEN a.jumlah ELSE 0 END),0) modal FROM `$table` a WHERE $scope GROUP BY a.kd_sub_keg,a.kd_akun ORDER BY a.kd_sub_keg,a.kd_akun",$p)->fetchAll();
    }
    public function monthlySummary(string $logical,?string $subCode=null):array
    {
        $subCode=$subCode??$this->currentSubCode;[$scope,$p]=$this->scope('r');$p[]=$logical;$extra='';if($subCode!==null){$extra=' AND r.kd_sub_keg=?';$p[]=$subCode;}$rows=$this->db->query("SELECT r.bulan,SUM(r.nilai) nilai FROM rencana_rekening_anggaran_neo r WHERE $scope AND r.dokumen=? AND r.jenis='belanja'$extra GROUP BY r.bulan ORDER BY r.bulan",$p)->fetchAll();$out=array_fill(1,12,0.0);foreach($rows as $r)$out[(int)$r['bulan']]=(float)$r['nilai'];return$out;
    }
    public function exportRecapExcel(string $logical):string
    {
        $rows=$this->recapRows($logical);$book=new Spreadsheet();$sheet=$book->getActiveSheet();$sheet->setTitle(strtoupper($logical).'-BELANJA');$last=$logical==='dppa'?'J':'H';$sheet->mergeCells("A1:{$last}1")->setCellValue('A1','REKAPITULASI DOKUMEN PELAKSANAAN '.($logical==='dppa'?'PERGESERAN ':'').'BELANJA BERDASARKAN PROGRAM, KEGIATAN, DAN SUB KEGIATAN');$headers=$logical==='dppa'?['KODE SUB KEGIATAN','URAIAN','KODE REKENING','SEBELUM','BELANJA OPERASI','BELANJA MODAL','SETELAH','BERTAMBAH/(BERKURANG)','%','KETERANGAN']:['KODE SUB KEGIATAN','URAIAN','KODE REKENING','BELANJA OPERASI','BELANJA MODAL','JUMLAH','SUMBER DANA','LOKASI'];$sheet->fromArray($headers,null,'A3');$r=4;foreach($rows as $x){if($logical==='dppa'){$delta=$x['sesudah']-$x['sebelum'];$sheet->fromArray([$x['kd_sub_keg'],$x['uraian'],$x['kd_akun'],$x['sebelum'],$x['operasi'],$x['modal'],$x['sesudah'],$delta,$x['sebelum']?($delta/$x['sebelum']):0,''],null,"A$r");}else $sheet->fromArray([$x['kd_sub_keg'],$x['uraian'],$x['kd_akun'],$x['operasi'],$x['modal'],$x['sesudah'],'',''],null,"A$r");$r++;}$sheet->getStyle("A1:{$last}1")->getFont()->setBold(true)->setSize(13)->getColor()->setARGB('FFFFFFFF');$sheet->getStyle("A1:{$last}1")->getFill()->setFillType('solid')->getStartColor()->setARGB('FF174A68');$sheet->getStyle("A3:{$last}3")->getFont()->setBold(true)->getColor()->setARGB('FFFFFFFF');$sheet->getStyle("A3:{$last}3")->getFill()->setFillType('solid')->getStartColor()->setARGB('FF2185D0');$sheet->getStyle("A3:{$last}".max(3,$r-1))->getBorders()->getAllBorders()->setBorderStyle(Border::BORDER_THIN);$sheet->getStyle("D4:I$r")->getNumberFormat()->setFormatCode('#,##0.00');foreach(range('A',$last) as $c)$sheet->getColumnDimension($c)->setWidth(in_array($c,['B','J'])?38:18);$sheet->freezePane('A4');$sheet->getPageSetup()->setOrientation('landscape')->setFitToWidth(1)->setFitToHeight(0);$tmp=tempnam(sys_get_temp_dir(),'rekap_').'.xlsx';(new Xlsx($book))->save($tmp);return$tmp;
    }

    public function exportPdf(string $logical):string
    {
        $groups=$this->groups($logical);$change=$this->isChange($logical);$orientation=$change?'L':'P';
        require_once __DIR__.'/../../vendor/tecnickcom/tcpdf/tcpdf.php';
        $pdf=new TCPDF($orientation,'mm','A4',true,'UTF-8',false);$pdf->SetCreator('seSendok');$pdf->SetAuthor((string)($this->user['nama_opd']??'Pemerintah Daerah'));$pdf->SetTitle($this->documentLabel($logical));$pdf->setPrintHeader(false);$pdf->setPrintFooter(true);$pdf->SetMargins(8,8,8);$pdf->SetAutoPageBreak(true,12);
        if(!$groups){$pdf->AddPage();$pdf->SetFont('helvetica','B',12);$pdf->Cell(0,10,'TIDAK ADA DATA DALAM LINGKUP PENGGUNA',0,1,'C');return $pdf->Output('','S');}
        foreach($groups as $group){$this->currentSubCode=(string)$group['kd_sub_keg'];$details=$this->details($logical,(string)$group['kd_sub_keg']);$pdf->AddPage();$pdf->SetFont('helvetica','',7.2);
            $title=$change?'DOKUMEN PELAKSANAAN PERGESERAN ANGGARAN':'DOKUMEN PELAKSANAAN ANGGARAN<br>SATUAN KERJA PERANGKAT DAERAH';
            $form=$change?'FORMULIR '.$this->documentLabel($logical).'<br>RINCIAN BELANJA SKPD':'FORMULIR '.$this->documentLabel($logical).'<br>RINCIAN BELANJA SKPD';
            $html='<table border="1" cellpadding="3"><tr><td width="72%" align="center" style="font-size:12px"><b>'.$title.'</b></td><td width="28%" align="center" style="font-size:10px"><b>'.$form.'</b></td></tr></table>';
            $html.='<table border="1" cellpadding="2">'.$this->metadataRows($group).'</table>';
            $html.='<table border="1" cellpadding="2"><tr><td width="25%"><b>Indikator</b></td><td width="45%"><b>Tolak Ukur Kinerja</b></td><td width="30%"><b>Target Kinerja</b></td></tr><tr><td>Capaian Sub Kegiatan</td><td>'.$this->e($group['nama_sub_kegiatan']??'-').'</td><td>'.$this->e(count($details)).' rincian belanja</td></tr></table>';
            if($change){$html.='<table border="1" cellpadding="2"><thead><tr style="background-color:#e8e8e8;font-weight:bold"><th width="11%" rowspan="2">Kode Rekening</th><th width="25%" rowspan="2">Uraian</th><th width="25%" colspan="3" align="center">Sebelum Perubahan</th><th width="25%" colspan="3" align="center">Sesudah Perubahan</th><th width="14%" rowspan="2">Bertambah/<br>(Berkurang)</th></tr><tr style="background-color:#e8e8e8;font-weight:bold"><th width="7%">Volume</th><th width="8%">Harga</th><th width="10%">Jumlah</th><th width="7%">Volume</th><th width="8%">Harga</th><th width="10%">Jumlah</th></tr></thead><tbody>';
                $before=0;$after=0;foreach($details as $d){$ba=(float)($d['jumlah_awal']??0);$aa=(float)($d['jumlah']??0);$before+=$ba;$after+=$aa;$html.='<tr><td>'.$this->e($d['kd_akun']??'-').'</td><td><b>'.$this->e($d['komponen']??$d['uraian']??'-').'</b><br>'.$this->e($d['spesifikasi']??'').'</td><td align="right">'.$this->money($d['volume_awal']??0).'</td><td align="right">'.$this->money($d['harga_satuan_awal']??0).'</td><td align="right">'.$this->money($ba).'</td><td align="right">'.$this->money($d['volume']??0).'</td><td align="right">'.$this->money($d['harga_satuan']??0).'</td><td align="right">'.$this->money($aa).'</td><td align="right">'.$this->money($aa-$ba).'</td></tr>';}$html.='<tr style="font-weight:bold"><td colspan="2">Jumlah Anggaran Sub Kegiatan</td><td colspan="3" align="right">'.$this->money($before).'</td><td colspan="3" align="right">'.$this->money($after).'</td><td align="right">'.$this->money($after-$before).'</td></tr></tbody></table>';
            }else{$html.='<table border="1" cellpadding="2"><thead><tr style="background-color:#e8e8e8;font-weight:bold"><th width="16%">Kode Rekening</th><th width="37%">Uraian</th><th width="12%">Koefisien/Volume</th><th width="10%">Satuan</th><th width="12%">Harga</th><th width="13%">Jumlah</th></tr></thead><tbody>';$total=0;foreach($details as $d){$total+=(float)($d['jumlah']??0);$html.='<tr><td>'.$this->e($d['kd_akun']??'-').'</td><td><b>'.$this->e($d['komponen']??$d['uraian']??'-').'</b><br>'.$this->e($d['spesifikasi']??'').'</td><td align="right">'.$this->money($d['volume']??0).'</td><td>'.$this->e($d['sat_1']??'-').'</td><td align="right">'.$this->money($d['harga_satuan']??0).'</td><td align="right">'.$this->money($d['jumlah']??0).'</td></tr>';}$html.='<tr style="font-weight:bold"><td colspan="5">Jumlah Anggaran Sub Kegiatan</td><td align="right">'.$this->money($total).'</td></tr></tbody></table>';}
            $signature=$this->e($this->user['nama_lengkap']??$this->user['nama']??'KEPALA SKPD');$months=$this->monthlySummary($logical);$names=['Januari','Februari','Maret','April','Mei','Juni','Juli','Agustus','September','Oktober','November','Desember'];$monthHtml='<table border="1" cellpadding="2"><tr style="font-weight:bold;background-color:#e8e8e8"><td>Bulan</td><td align="right">Rencana Penarikan Dana</td></tr>';foreach($months as $m=>$v)$monthHtml.='<tr><td>'.$names[$m-1].'</td><td align="right">Rp'.$this->money($v).'</td></tr>';$monthHtml.='<tr style="font-weight:bold"><td>Jumlah</td><td align="right">Rp'.$this->money(array_sum($months)).'</td></tr></table>';$html.='<br><table cellpadding="3"><tr><td width="50%"><b>Rencana Penarikan Dana per Bulan</b>'.$monthHtml.'</td><td width="50%" align="center">'.date('d-m-Y').'<br>Kepala SKPD<br><br><br><b><u>'.$signature.'</u></b><br>NIP. ................................</td></tr></table>';
            $tapd=$this->activeTapd();$html.='<br><b>Tim Anggaran Pemerintah Daerah</b><table border="1" cellpadding="2"><tr style="font-weight:bold;background-color:#e8e8e8"><td width="6%">No.</td><td width="34%">Nama</td><td width="24%">NIP</td><td width="24%">Jabatan</td><td width="12%">Tanda Tangan</td></tr>';foreach($tapd as $i=>$person)$html.='<tr><td>'.($i+1).'.</td><td>'.$this->e($person['nama']).'</td><td>'.$this->e($person['nip']).'</td><td>'.$this->e($person['jabatan']).'</td><td></td></tr>';if(!$tapd)$html.='<tr><td colspan="5">Belum ada penugasan TAPD yang berlaku pada tanggal cetak.</td></tr>';$html.='</table>';
            $pdf->writeHTML($html,true,false,true,false,'');
        }return $pdf->Output('','S');
    }

    public function exportOfficialPdf(string $logical):string
    {
        $groups=$this->groups($logical);$change=$this->isChange($logical);require_once __DIR__.'/../../vendor/tecnickcom/tcpdf/tcpdf.php';$pdf=new TCPDF('L','mm','A4',true,'UTF-8',false);$pdf->setPrintHeader(false);$pdf->setPrintFooter(true);$pdf->SetMargins(7,7,7);$pdf->SetAutoPageBreak(true,10);$pdf->SetFont('helvetica','',6.8);
        foreach($groups as $group){$code=(string)$group['kd_sub_keg'];$this->currentSubCode=$code;$details=$this->details($logical,$code);$pdf->AddPage();$label=$this->documentLabel($logical);$html='<table border="1" cellpadding="2"><tr><td width="72%" align="center" style="font-size:11px"><b>'.($change?'DOKUMEN PELAKSANAAN PERGESERAN ANGGARAN':'DOKUMEN PELAKSANAAN ANGGARAN').'<br>SATUAN KERJA PERANGKAT DAERAH</b></td><td width="28%" align="center" style="font-size:9px"><b>FORMULIR '.$this->e($label).'<br>RINCIAN BELANJA SKPD</b></td></tr></table><table border="1" cellpadding="2">'.$this->metadataRows($group).'</table>';
            if($change)$html.='<table border="1" cellpadding="2"><thead><tr style="font-weight:bold;background-color:#e7e7e7"><th width="12%" rowspan="2">Kode Rekening</th><th width="28%" rowspan="2">Uraian</th><th width="24%" colspan="3" align="center">Sebelum Perubahan</th><th width="24%" colspan="3" align="center">Sesudah Perubahan</th><th width="12%" rowspan="2">Bertambah/<br>(Berkurang)</th></tr><tr style="font-weight:bold;background-color:#e7e7e7"><th width="7%">Volume</th><th width="8%">Harga</th><th width="9%">Jumlah</th><th width="7%">Volume</th><th width="8%">Harga</th><th width="9%">Jumlah</th></tr></thead><tbody>';
            else $html.='<table border="1" cellpadding="2"><thead><tr style="font-weight:bold;background-color:#e7e7e7"><th width="14%">Kode Rekening</th><th width="38%">Uraian</th><th width="12%">Koefisien/Volume</th><th width="10%">Satuan</th><th width="13%">Harga</th><th width="13%">Jumlah</th></tr></thead><tbody>';
            $last='';$before=0;$after=0;foreach($details as $d){$account=(string)($d['kd_akun']??'');if($account!==$last){$html.=$this->hierarchyHtml($account,$change?9:6);$last=$account;}$ba=(float)($d['jumlah_awal']??0);$aa=(float)($d['jumlah']??0);$before+=$ba;$after+=$aa;$description='<b>'.$this->e($d['komponen']??$d['uraian']??'-').'</b>'.(!empty($d['spesifikasi'])?'<br>Spesifikasi: '.$this->e($d['spesifikasi']):'');if($change)$html.='<tr><td></td><td>'.$description.'</td><td align="right">'.$this->money($d['volume_awal']??0).'</td><td align="right">'.$this->money($d['harga_satuan_awal']??0).'</td><td align="right">'.$this->money($ba).'</td><td align="right">'.$this->money($d['volume']??0).'</td><td align="right">'.$this->money($d['harga_satuan']??0).'</td><td align="right">'.$this->money($aa).'</td><td align="right">'.$this->money($aa-$ba).'</td></tr>';else $html.='<tr><td></td><td>'.$description.'</td><td align="right">'.$this->money($d['volume']??0).'</td><td>'.$this->e($d['sat_1']??'-').'</td><td align="right">'.$this->money($d['harga_satuan']??0).'</td><td align="right">'.$this->money($aa).'</td></tr>';}
            $html.=$change?'<tr style="font-weight:bold"><td colspan="2">Jumlah Anggaran Sub Kegiatan</td><td colspan="3" align="right">'.$this->money($before).'</td><td colspan="3" align="right">'.$this->money($after).'</td><td align="right">'.$this->money($after-$before).'</td></tr></tbody></table>':'<tr style="font-weight:bold"><td colspan="5">Jumlah Anggaran Sub Kegiatan</td><td align="right">'.$this->money($after).'</td></tr></tbody></table>';
            $months=$this->monthlySummary($logical,$code);$names=['Januari','Februari','Maret','April','Mei','Juni','Juli','Agustus','September','Oktober','November','Desember'];$html.='<br><table cellpadding="2"><tr><td width="50%"><b>Rencana Penarikan Dana per Bulan</b><table border="1" cellpadding="1">';foreach($months as $m=>$v)$html.='<tr><td>'.$names[$m-1].'</td><td align="right">Rp'.$this->money($v).'</td></tr>';$html.='<tr style="font-weight:bold"><td>Jumlah</td><td align="right">Rp'.$this->money(array_sum($months)).'</td></tr></table></td><td width="50%" align="center">'.date('d-m-Y').'<br>Kepala SKPD<br><br><br><b><u>'.$this->e($this->user['nama_lengkap']??$this->user['nama']??'KEPALA SKPD').'</u></b><br>NIP. ................................</td></tr></table>';
            $tapd=$this->activeTapd();$html.='<br><b>Tim Anggaran Pemerintah Daerah</b><table border="1" cellpadding="2"><tr style="font-weight:bold;background-color:#e7e7e7"><td width="6%">No.</td><td width="34%">Nama</td><td width="25%">NIP</td><td width="23%">Jabatan</td><td width="12%">Tanda Tangan</td></tr>';foreach($tapd as $i=>$p)$html.='<tr><td>'.($i+1).'.</td><td>'.$this->e($p['nama']).'</td><td>'.$this->e($p['nip']).'</td><td>'.$this->e($p['jabatan']).'</td><td></td></tr>';$html.='</table>';$pdf->writeHTML($html,true,false,true,false,'');}
        return$pdf->Output('','S');
    }
    public function exportRecapPdf(string $logical):string
    {
        $rows=$this->recapRows($logical);require_once __DIR__.'/../../vendor/tecnickcom/tcpdf/tcpdf.php';$pdf=new TCPDF('L','mm','A4',true,'UTF-8',false);$pdf->setPrintHeader(false);$pdf->SetMargins(7,7,7);$pdf->AddPage();$pdf->SetFont('helvetica','',7);$change=$logical==='dppa';$html='<h2 align="center">DOKUMEN PELAKSANAAN '.($change?'PERGESERAN ':'').'ANGGARAN<br>REKAPITULASI BELANJA BERDASARKAN PROGRAM, KEGIATAN, DAN SUB KEGIATAN</h2><table border="1" cellpadding="2"><tr style="font-weight:bold;background-color:#e8e8e8"><td width="13%">Kode Sub Kegiatan</td><td width="25%">Uraian</td><td width="12%">Kode Rekening</td>'.($change?'<td width="12%">Sebelum</td>':'').'<td width="12%">Belanja Operasi</td><td width="12%">Belanja Modal</td><td width="12%">Jumlah</td>'.($change?'<td width="12%">Bertambah/(Berkurang)</td>':'').'</tr>';$total=0;foreach($rows as $r){$delta=(float)$r['sesudah']-(float)$r['sebelum'];$total+=(float)$r['sesudah'];$html.='<tr><td>'.$this->e($r['kd_sub_keg']).'</td><td>'.$this->e($r['uraian']).'</td><td>'.$this->e($r['kd_akun']).'</td>'.($change?'<td align="right">'.$this->money($r['sebelum']).'</td>':'').'<td align="right">'.$this->money($r['operasi']).'</td><td align="right">'.$this->money($r['modal']).'</td><td align="right">'.$this->money($r['sesudah']).'</td>'.($change?'<td align="right">'.$this->money($delta).'</td>':'').'</tr>';}$html.='<tr style="font-weight:bold"><td colspan="'.($change?6:5).'">JUMLAH BELANJA</td><td align="right">'.$this->money($total).'</td>'.($change?'<td></td>':'').'</tr></table>';$pdf->writeHTML($html,true,false,true,false,'');return$pdf->Output('','S');
    }

    public function exportRegulatoryPdf(string $logical):string
    {
        $groups=$this->groups($logical);$change=$this->isChange($logical);require_once __DIR__.'/../../vendor/tecnickcom/tcpdf/tcpdf.php';
        $pdf=new TCPDF($change?'L':'P','mm','A4',true,'UTF-8',false);$pdf->setPrintHeader(false);$pdf->setPrintFooter(true);$pdf->SetMargins(7,7,7);$pdf->SetAutoPageBreak(true,10);$pdf->SetFont('helvetica','',6.4);
        if(!$groups){$pdf->AddPage();$pdf->Cell(0,8,'TIDAK ADA DATA DALAM LINGKUP PENGGUNA',0,1,'C');return$pdf->Output('','S');}
        foreach($groups as $group){$details=$this->details($logical,(string)$group['kd_sub_keg']);$pdf->AddPage();$label=$this->documentLabel($logical);$heading=$change?'DOKUMEN PELAKSANAAN PERGESERAN ANGGARAN':'DOKUMEN PELAKSANAAN ANGGARAN';
            $html='<table border="1" cellpadding="2"><tr><td width="72%" align="center" style="font-size:10px"><b>'.$heading.'<br>SATUAN KERJA PERANGKAT DAERAH</b></td><td width="28%" align="center" style="font-size:8px"><b>FORMULIR<br>'.$this->e($label).' RINCIAN BELANJA SKPD</b></td></tr></table><table border="1" cellpadding="2">'.$this->metadataRows($group).'</table>';
            if($change)$html.='<table border="1" cellpadding="2"><thead><tr style="font-weight:bold;background-color:#e8e8e8"><th width="11%" rowspan="2">Kode Rekening</th><th width="19%" rowspan="2">Uraian</th><th width="29.5%" colspan="5" align="center">Sebelum</th><th width="29.5%" colspan="5" align="center">Setelah</th><th width="11%" rowspan="2">Bertambah/<br>Berkurang (Rp)</th></tr><tr style="font-weight:bold;background-color:#e8e8e8"><th width="8%">Koefisien / Volume</th><th width="5%">Satuan</th><th width="7%">Harga</th><th width="3.5%">PPN</th><th width="6%">Jumlah</th><th width="8%">Koefisien / Volume</th><th width="5%">Satuan</th><th width="7%">Harga</th><th width="3.5%">PPN</th><th width="6%">Jumlah</th></tr></thead><tbody>';
            else$html.='<table border="1" cellpadding="2"><thead><tr style="font-weight:bold;background-color:#e8e8e8"><th width="14%">Kode Rekening</th><th width="36%">Uraian</th><th width="12%">Koefisien / Volume</th><th width="8%">Satuan</th><th width="12%">Harga</th><th width="6%">PPN</th><th width="12%">Jumlah</th></tr></thead><tbody>';
            $last='';$before=$after=0;foreach($details as $d){$account=(string)($d['kd_akun']??'');if($account!==$last){$html.=$this->hierarchyHtml($account,$change?13:7);$last=$account;}$ba=(float)($d['jumlah_awal']??0);$aa=(float)($d['jumlah']??0);$before+=$ba;$after+=$aa;$description='<b>'.$this->e($d['komponen']??$d['uraian']??'-').'</b>'.(!empty($d['spesifikasi'])?'<br>Spesifikasi: '.$this->e($d['spesifikasi']):'');$unit=$this->e($d['sat_1']??'-');if($change)$html.='<tr><td></td><td>'.$description.'</td><td align="right">'.$this->money($d['volume_awal']??0).'</td><td>'.$unit.'</td><td align="right">'.$this->money($d['harga_satuan_awal']??0).'</td><td align="center">0%</td><td align="right">'.$this->money($ba).'</td><td align="right">'.$this->money($d['volume']??0).'</td><td>'.$unit.'</td><td align="right">'.$this->money($d['harga_satuan']??0).'</td><td align="center">0%</td><td align="right">'.$this->money($aa).'</td><td align="right">'.$this->money($aa-$ba).'</td></tr>';else$html.='<tr><td></td><td>'.$description.'</td><td align="right">'.$this->money($d['volume']??0).'</td><td>'.$unit.'</td><td align="right">'.$this->money($d['harga_satuan']??0).'</td><td align="center">0%</td><td align="right">'.$this->money($aa).'</td></tr>';}
            $html.=$change?'<tr style="font-weight:bold"><td colspan="2">Jumlah Anggaran Sub Kegiatan</td><td colspan="5" align="right">'.$this->money($before).'</td><td colspan="5" align="right">'.$this->money($after).'</td><td align="right">'.$this->money($after-$before).'</td></tr></tbody></table>':'<tr style="font-weight:bold"><td colspan="6">Jumlah Anggaran Sub Kegiatan</td><td align="right">'.$this->money($after).'</td></tr></tbody></table>';
            $pdf->writeHTML($html,true,false,true,false,'');
        }return$pdf->Output('','S');
    }
    public function exportExcel(string $logical):string
    {
        $groups=$this->groups($logical);$book=new Spreadsheet();$book->removeSheetByIndex(0);$used=[];$change=$this->isChange($logical);
        foreach($groups as $index=>$group){$code=(string)$group['kd_sub_keg'];$name=str_replace(['\\','/','?','*','[',']',':'],'-',substr($code,0,25))?:'SubKegiatan-'.($index+1);while(isset($used[$name]))$name=substr($name,0,28).'-'.($index+1);$used[$name]=1;$sheet=$book->createSheet();$sheet->setTitle($name);$details=$this->details($logical,$code);$last=$change?'I':'F';$sheet->mergeCells("A1:{$last}1")->setCellValue('A1','DOKUMEN PELAKSANAAN '.($change?'PERGESERAN ':'').'ANGGARAN — '.$this->documentLabel($logical));$sheet->mergeCells("A2:{$last}2")->setCellValue('A2','FORMULIR RINCIAN BELANJA SKPD');$sheet->mergeCells("A3:{$last}3")->setCellValue('A3','Sub Kegiatan: '.$code.' '.($group['nama_sub_kegiatan']??''));$sheet->mergeCells("A4:{$last}4")->setCellValue('A4','Program: '.($group['program']??'-').' | Kegiatan: '.($group['kegiatan']??'-'));
            if($change){$sheet->mergeCells('A6:A7')->mergeCells('B6:B7')->mergeCells('C6:E6')->mergeCells('F6:H6')->mergeCells('I6:I7');$sheet->fromArray(['KODE REKENING','URAIAN','SEBELUM PERUBAHAN','','','SESUDAH PERUBAHAN','','','BERTAMBAH/(BERKURANG)'],null,'A6');$sheet->fromArray(['','','VOLUME','HARGA','JUMLAH','VOLUME','HARGA','JUMLAH',''],null,'A7');$row=8;$before=$after=0;foreach($details as $d){$ba=(float)($d['jumlah_awal']??0);$aa=(float)($d['jumlah']??0);$before+=$ba;$after+=$aa;$sheet->fromArray([$d['kd_akun']??'-',trim(($d['komponen']??$d['uraian']??'').' '.($d['spesifikasi']??'')),(float)($d['volume_awal']??0),(float)($d['harga_satuan_awal']??0),$ba,(float)($d['volume']??0),(float)($d['harga_satuan']??0),$aa,$aa-$ba],null,'A'.$row++);}$sheet->fromArray(['JUMLAH ANGGARAN SUB KEGIATAN','',$before,'','',$after,'','',$after-$before],null,'A'.$row);$header='A6:I7';$range="A6:I$row";$money="C8:I$row";
            }else{$sheet->fromArray(['KODE REKENING','URAIAN','KOEFISIEN/VOLUME','SATUAN','HARGA','JUMLAH'],null,'A6');$row=7;$total=0;foreach($details as $d){$total+=(float)($d['jumlah']??0);$sheet->fromArray([$d['kd_akun']??'-',trim(($d['komponen']??$d['uraian']??'').' '.($d['spesifikasi']??'')),(float)($d['volume']??0),$d['sat_1']??'-',(float)($d['harga_satuan']??0),(float)($d['jumlah']??0)],null,'A'.$row++);}$sheet->fromArray(['JUMLAH ANGGARAN SUB KEGIATAN','','','','',$total],null,'A'.$row);$header='A6:F6';$range="A6:F$row";$money="C7:F$row";}
            $sheet->getStyle("A1:{$last}1")->getFont()->setBold(true)->setSize(14)->getColor()->setARGB('FFFFFFFF');$sheet->getStyle("A1:{$last}1")->getFill()->setFillType('solid')->getStartColor()->setARGB('FF174A68');$sheet->getStyle('A2:'.$last.'4')->getFont()->setBold(true);$sheet->getStyle($header)->getFont()->setBold(true)->getColor()->setARGB('FFFFFFFF');$sheet->getStyle($header)->getFill()->setFillType('solid')->getStartColor()->setARGB('FF2185D0');$sheet->getStyle($range)->getBorders()->getAllBorders()->setBorderStyle(Border::BORDER_THIN)->getColor()->setARGB('FF708090');$sheet->getStyle($money)->getNumberFormat()->setFormatCode('#,##0.00');$sheet->getStyle("A1:{$last}{$row}")->getAlignment()->setVertical(Alignment::VERTICAL_TOP)->setWrapText(true);$sheet->getStyle("A$row:{$last}{$row}")->getFont()->setBold(true);$sheet->freezePane($change?'A8':'A7');foreach(['A'=>19,'B'=>48,'C'=>15,'D'=>15,'E'=>18,'F'=>15,'G'=>15,'H'=>18,'I'=>20] as $col=>$width)$sheet->getColumnDimension($col)->setWidth($width);$sheet->getPageSetup()->setOrientation($change?'landscape':'portrait')->setFitToWidth(1)->setFitToHeight(0);}
        if(!$groups){$sheet=$book->createSheet();$sheet->setTitle('Kosong');$sheet->setCellValue('A1','Tidak ada data dalam lingkup pengguna.');}$book->setActiveSheetIndex(0);$tmp=tempnam(sys_get_temp_dir(),'anggaran_').'.xlsx';(new Xlsx($book))->save($tmp);return $tmp;
    }
}
