<?php
require_once __DIR__.'/PageSetupService.php';
require_once __DIR__.'/OfficialLetterheadPdfService.php';

/** Layout khusus untuk setiap dokumen pada ZIP contoh pengguna. */
final class ProcurementZipPdfService
{
    private const CODES=['UNDANGAN_PL','JADWAL_DOKUMEN','BA_SURVEY_HARGA','PAKTA_INTEGRITAS','BA_KLARIFIKASI_NEGOSIASI','LAMPIRAN_NEGOSIASI','DAFTAR_HADIR_KLARIFIKASI','PENETAPAN_PENYEDIA','PENGUMUMAN_PENYEDIA','BA_EVALUASI','BAHP','SPPBJ','SPMK','RAPAT_PRA_KONTRAK'];
    private array $user; private string $font='helvetica'; private float $size=9;
    public function __construct(array $user){$this->user=$user;}
    public function supports(string $code):bool{return in_array(strtoupper($code),self::CODES,true);}
    public function render(string $code,array $d,array $c,array $setup):string
    {
        $this->font=(string)($setup['font']??'helvetica');$this->size=(float)($setup['font_size']??9);
        return match(strtoupper($code)){
            'UNDANGAN_PL'=>$this->invitation($d,$c,$setup),'JADWAL_DOKUMEN'=>$this->documentSchedule($d,$c,$setup),
            'BA_SURVEY_HARGA'=>$this->survey($d,$c,$setup),'PAKTA_INTEGRITAS'=>$this->integrity($d,$c,$setup),
            'BA_KLARIFIKASI_NEGOSIASI'=>$this->negotiation($d,$c,$setup),'LAMPIRAN_NEGOSIASI'=>$this->negotiationAttachment($d,$c,$setup),
            'DAFTAR_HADIR_KLARIFIKASI'=>$this->attendance($d,$c,$setup),'PENETAPAN_PENYEDIA'=>$this->providerDecision($d,$c,$setup),
            'PENGUMUMAN_PENYEDIA'=>$this->announcement($d,$c,$setup),'BA_EVALUASI'=>$this->evaluation($d,$c,$setup,false),
            'BAHP'=>$this->evaluation($d,$c,$setup,true),'SPPBJ'=>$this->sppbj($d,$c,$setup),
            'SPMK'=>$this->spmk($d,$c,$setup),'RAPAT_PRA_KONTRAK'=>$this->preContract($d,$c,$setup)
        };
    }
    private function pdf(array $setup,string $orientation='P'):TCPDF{$pdf=PageSetupService::createPdf($setup,$orientation);PageSetupService::applyPdf($pdf,$setup,[18,15,18,18]);$pdf->SetFont($this->font,'',$this->size);return$pdf;}
    private function page(array $setup,string $orientation='P',bool $letterhead=true):TCPDF{$pdf=$this->pdf($setup,$orientation);$pdf->AddPage();if($letterhead)OfficialLetterheadPdfService::draw($pdf,$this->user);return$pdf;}
    private function e(mixed $v):string{return htmlspecialchars((string)$v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}
    private function v(array $data,string ...$keys):string{foreach($keys as $key){$value=trim((string)($data[$key]??''));if($value!=='')return$value;}return'-';}
    private function money(mixed $v):string{return'Rp'.number_format((float)$v,2,',','.');}
    private function date(array $d,array $c):string{$raw=$d['tanggal_dokumen']??$c['tanggal_kontrak']??date('Y-m-d');$time=strtotime((string)$raw);if(!$time)return(string)$raw;$months=[1=>'Januari','Februari','Maret','April','Mei','Juni','Juli','Agustus','September','Oktober','November','Desember'];return date('j',$time).' '.$months[(int)date('n',$time)].' '.date('Y',$time);}
    private function title(TCPDF $pdf,string $title,string $number=''):void{$pdf->SetFont($this->font,'B',$this->size+3);$pdf->MultiCell(0,6,strtoupper($title),0,'C');if($number!==''){$pdf->SetFont($this->font,'',$this->size);$pdf->MultiCell(0,5,'Nomor : '.$number,0,'C');}$pdf->Ln(3);}
    private function para(TCPDF $pdf,string $text,float $height=5.0):void{$pdf->MultiCell(0,$height,rtrim($text)."\n",0,'J',false,1,'','',true,0,false,true);}
    private function fields(array $rows,array $widths=[30,4,66]):string{$html='<table cellpadding="3">';foreach($rows as [$label,$value])$html.='<tr><td width="'.$widths[0].'%">'.$this->e($label).'</td><td width="'.$widths[1].'%">:</td><td width="'.$widths[2].'%">'.$this->e($value).'</td></tr>';$html.='</table>';return$html;}
    private function signature(TCPDF $pdf,string $role,string $name,string $nip=''):void{$pdf->Ln(6);$html='<table><tr><td width="55%"></td><td width="45%" align="center">'.nl2br($this->e($role)).'<br><br><br><br><b><u>'.$this->e($name).'</u></b>'.($nip!==''?'<br>NIP. '.$this->e($nip):'').'</td></tr></table>';$pdf->writeHTML($html,true,false,true,false,'');}
    private function package(array $c):array{return[['Sub Kegiatan',$this->v($c,'nama_sub_kegiatan','nama_sub_keg','kd_sub_keg')],['Nama Paket',$this->v($c,'uraian_kontrak')],['Sumber Dana',$this->v($c,'sumber_dana')],['Tahun Anggaran',$this->v($c,'tahun')],['Kode Rekening',$this->v($c,'kd_sub_keg')],['Nilai HPS/OE',$this->money($c['nilai_kontrak']??0)]];}
    private function provider(array $c):array{return[['Nama Penyedia Barang/Jasa',$this->v($c,'nama_penyedia_resmi','nama_perusahaan','nama_penyedia')],['Nama Direktur',$this->v($c,'direktur')],['Alamat',$this->v($c,'alamat_penyedia','alamat')],['NPWP',$this->v($c,'npwp')],['Harga Klarifikasi dan Negosiasi',$this->money($c['nilai_kontrak']??0)],['Jangka waktu pelaksanaan',$this->v($c,'waktu_pelaksanaan').' hari kalender']];}
    private function invitation(array $d,array $c,array $setup):string
    {
        $pdf=$this->page($setup);$date=$this->date($d,$c);$provider=$this->v($c,'nama_penyedia_resmi','nama_perusahaan','nama_penyedia');$address=$this->v($c,'alamat_penyedia','alamat');
        $pdf->writeHTML('<table cellpadding="2"><tr><td width="62%">Nomor &nbsp;&nbsp;&nbsp;: '.$this->e($d['nomor_dokumen']??'-').'<br>Lampiran : 1 (satu) berkas</td><td width="38%">Pasangkayu, '.$this->e($date).'</td></tr></table><br><b>Kepada Yth.<br>Direktur '.$this->e($provider).'<br>di-<br>'.$this->e($address).'</b><br><br><b>Perihal: Undangan Pengadaan Langsung '.$this->e($this->v($c,'uraian_kontrak')).'</b><br><br>',true,false,true,false,'');
        $this->para($pdf,'Dengan ini, perusahaan Saudara kami undang untuk mengikuti proses Pengadaan Langsung paket pekerjaan sebagai berikut:',5);$pdf->writeHTML('<b>1. Paket Pekerjaan</b>'.$this->fields($this->package($c)).'<b>2. Pelaksanaan Pengadaan</b>'.$this->fields([['Tempat dan alamat',$this->v($this->user,'nama_opd').' - '.$this->v($this->user,'alamat_opd')]]).'<br>Saudara diminta memasukkan penawaran administrasi, teknis dan harga secara langsung sesuai jadwal berikut:<br><table border="1" cellpadding="4"><tr><th width="8%">No.</th><th width="42%">Kegiatan</th><th width="30%">Hari/Tanggal</th><th width="20%">Waktu</th></tr><tr><td>1</td><td>Undangan</td><td>'.$this->e($date).'</td><td>s.d. selesai</td></tr><tr><td>2</td><td>Pemasukan Dokumen Penawaran</td><td>'.$this->e($date).'</td><td>s.d. selesai</td></tr><tr><td>3</td><td>Pembukaan Dokumen Penawaran</td><td>'.$this->e($date).'</td><td>s.d. selesai</td></tr><tr><td>4</td><td>Klarifikasi Teknis dan Negosiasi Harga</td><td>'.$this->e($date).'</td><td>s.d. selesai</td></tr><tr><td>5</td><td>Penandatanganan SPK</td><td>'.$this->e($date).'</td><td>s.d. selesai</td></tr></table><br>Demikian disampaikan untuk diketahui.',true,false,true,false,'');$this->signature($pdf,'Pejabat Pengadaan Barang/Jasa',$this->v($this->user,'nama_pejabat_pengadaan','nama_user'),$this->v($this->user,'nip_pejabat_pengadaan','nip'));return$pdf->Output('','S');
    }
    private function documentSchedule(array $d,array $c,array $setup):string
    {
        $pdf=$this->page($setup,'L',false);$this->title($pdf,'Jadwal dan Kelengkapan Dokumen Pengadaan Melalui Proses Pengadaan Langsung');$date=$this->date($d,$c);$items=['Undangan','Pemasukan Dokumen Penawaran','Pembukaan Dokumen Penawaran','Evaluasi Penawaran','Evaluasi Kualifikasi','BA Klarifikasi dan Negosiasi','Daftar Hadir Klarifikasi dan Negosiasi','Lampiran Biaya Setelah Negosiasi','BA Hasil Pengadaan Langsung','Penetapan Penyedia','Pengumuman Penyedia','SPPBJ','SPMK','SPK'];$html='<table border="1" cellpadding="4"><tr style="font-weight:bold"><th width="6%">No.</th><th width="44%">URAIAN</th><th width="18%">HARI/TANGGAL</th><th width="22%">NOMOR</th><th width="5%">ADA</th><th width="5%">TDK</th></tr>';foreach($items as $i=>$item)$html.='<tr><td>'.($i+1).'</td><td>'.$this->e($item).'</td><td>'.$this->e($date).'</td><td>'.($i===0?$this->e($d['nomor_dokumen']??'-'):'').'</td><td></td><td></td></tr>';$pdf->writeHTML($html.'</table>',true,false,true,false,'');return$pdf->Output('','S');
    }
    private function survey(array $d,array $c,array $setup):string
    {
        $pdf=$this->page($setup);$this->title($pdf,'Berita Acara Survey Harga',$d['nomor_dokumen']??'');$this->para($pdf,'Pada hari ini tanggal '.$this->date($d,$c).', yang bertanda tangan di bawah ini Pejabat Pengadaan Barang/Jasa pada '.$this->v($this->user,'nama_opd').' yang ditetapkan berdasarkan Surat Keputusan Kepala Perangkat Daerah tentang Penunjukan Pejabat Pengadaan Tahun '.$this->v($c,'tahun').', telah mengadakan survei harga untuk:',5);$pdf->writeHTML($this->fields([['Sub Kegiatan',$this->v($c,'nama_sub_kegiatan','nama_sub_keg','kd_sub_keg')],['Nama Paket',$this->v($c,'uraian_kontrak')],['Ruas Pekerjaan',$this->v($c,'uraian_kontrak')]]).'<br><b>Dengan hasil sebagai berikut:</b><ol><li>Survei pertama dilakukan dengan hasil terlampir.</li><li>Survei kedua dilakukan dengan hasil terlampir.</li></ol><br>Demikian Berita Acara ini dibuat dalam rangkap 3 (tiga) untuk dapat dipergunakan sebagaimana mestinya.',true,false,true,false,'');$this->signature($pdf,'Pejabat Pengadaan Barang/Jasa',$this->v($this->user,'nama_pejabat_pengadaan','nama_user'),$this->v($this->user,'nip_pejabat_pengadaan','nip'));return$pdf->Output('','S');
    }
    private function integrity(array $d,array $c,array $setup):string
    {
        $pdf=$this->page($setup);$this->title($pdf,'Pakta Integritas');$this->para($pdf,'Saya yang bertanda tangan di bawah ini, dalam rangka '.$this->v($c,'uraian_kontrak').' pada '.$this->v($this->user,'nama_opd').' Tahun Anggaran '.$this->v($c,'tahun').', menyatakan bahwa saya:',5);$pdf->writeHTML('<ol><li>Tidak akan melakukan praktik korupsi, kolusi, dan nepotisme.</li><li>Akan melaporkan kepada pihak berwenang apabila mengetahui indikasi KKN dalam proses pengadaan.</li><li>Akan melaksanakan tugas secara bersih, transparan, profesional, dan mengerahkan sumber daya secara optimal.</li><li>Bersedia menerima sanksi apabila melanggar Pakta Integritas ini.</li></ol><br>Demikian Pakta Integritas ini dibuat dengan sebenarnya.',true,false,true,false,'');$pdf->writeHTML('<br><table cellpadding="5"><tr><th width="7%">No.</th><th width="43%">Pihak</th><th width="30%">Nama</th><th width="20%">Tanda Tangan</th></tr><tr><td>1.</td><td>Pejabat Pembuat Komitmen</td><td>'.$this->e($this->v($c,'nama_ppk_resmi','nama_ppk')).'</td><td>....................</td></tr><tr><td>2.</td><td>Pejabat Pelaksana Teknis Kegiatan</td><td>-</td><td>....................</td></tr><tr><td>3.</td><td>Pejabat Pengadaan Barang/Jasa</td><td>'.$this->e($this->v($this->user,'nama_pejabat_pengadaan','nama_user')).'</td><td>....................</td></tr></table>',true,false,true,false,'');return$pdf->Output('','S');
    }
    private function negotiation(array $d,array $c,array $setup):string
    {
        $pdf=$this->page($setup);$this->title($pdf,"Berita Acara\nHasil Klarifikasi dan Negosiasi",$d['nomor_dokumen']??'');$this->para($pdf,'Pada tanggal '.$this->date($d,$c).' bertempat di '.$this->v($this->user,'nama_opd').', Pejabat Pengadaan Barang/Jasa yang ditetapkan berdasarkan Surat Keputusan Kepala Perangkat Daerah telah melakukan klarifikasi dan negosiasi untuk:',5);$pdf->writeHTML($this->fields($this->package($c)).'<br><b>Dengan hasil sebagai berikut:</b><ol><li>Klarifikasi dan negosiasi dilaksanakan antara Pejabat Pengadaan Barang/Jasa dengan Direktur '.$this->e($this->v($c,'nama_penyedia_resmi','nama_penyedia')).'.</li><li>Klarifikasi dan negosiasi dilakukan untuk mendapatkan kesepakatan besarnya biaya dengan tetap mempertahankan hasil yang ingin dicapai berdasarkan penawaran teknis.</li><li>Sebagai hasil klarifikasi dan negosiasi:<ol><li>Dokumen penawaran Penyedia telah sesuai dengan persyaratan Dokumen Pemilihan/KAK.</li><li>Penyedia sepakat dengan nilai hasil negosiasi sebesar '.$this->money($c['nilai_kontrak']??0).'. Lampiran rincian penawaran setelah klarifikasi dan negosiasi merupakan bagian yang tidak terpisahkan dari berita acara ini.</li><li>Nilai biaya yang disepakati tetap memenuhi persyaratan teknis yang ditentukan dalam Dokumen Pemilihan/KAK.</li></ol></li></ol><br>Demikian Berita Acara Hasil Klarifikasi dan Negosiasi ini dibuat dengan sebenarnya dan ditandatangani para pihak untuk dipergunakan sebagaimana mestinya.',true,false,true,false,'');$pdf->writeHTML('<table><tr><td width="50%" align="center">Penyedia Barang/Jasa<br>'.$this->e($this->v($c,'nama_penyedia_resmi','nama_penyedia')).'<br><br><br><b><u>'.$this->e($this->v($c,'direktur')).'</u></b><br>Direktur</td><td width="50%" align="center">Pejabat Pengadaan Barang/Jasa<br><br><br><br><b><u>'.$this->e($this->v($this->user,'nama_pejabat_pengadaan','nama_user')).'</u></b><br>NIP. '.$this->e($this->v($this->user,'nip_pejabat_pengadaan','nip')).'</td></tr></table>',true,false,true,false,'');return$pdf->Output('','S');
    }
    private function negotiationAttachment(array $d,array $c,array $setup):string
    {
        $pdf=$this->page($setup,'L',false);$pdf->SetFont($this->font,'B',$this->size);$pdf->MultiCell(0,5,"LAMPIRAN I\nBerita Acara Klarifikasi dan Negosiasi\nNomor: ".($d['nomor_dokumen']??'-').'   Tanggal: '.$this->date($d,$c),0,'L');$this->title($pdf,'Rincian Penawaran Setelah Klarifikasi dan Negosiasi');$html='<table border="1" cellpadding="3"><tr style="font-weight:bold"><th rowspan="2" width="5%">No.</th><th rowspan="2" width="28%">Uraian Pekerjaan</th><th colspan="3" width="18%">Kuantitas</th><th rowspan="2" width="8%">Satuan</th><th colspan="3" width="24%">Harga Satuan</th><th rowspan="2" width="5%">Pajak</th><th colspan="3" width="12%">Jumlah</th></tr><tr><th>HPS</th><th>Penawaran</th><th>Negosiasi</th><th>HPS</th><th>Penawaran</th><th>Negosiasi</th><th>HPS</th><th>Penawaran</th><th>Negosiasi</th></tr><tr><td>1</td><td>'.$this->e($this->v($c,'uraian_kontrak')).'</td><td>1,00</td><td>1,00</td><td>1,00</td><td>LS</td><td>'.$this->money($c['nilai_kontrak']??0).'</td><td>'.$this->money($c['nilai_kontrak']??0).'</td><td>'.$this->money($c['nilai_kontrak']??0).'</td><td>11%</td><td>'.$this->money($c['nilai_kontrak']??0).'</td><td>'.$this->money($c['nilai_kontrak']??0).'</td><td>'.$this->money($c['nilai_kontrak']??0).'</td></tr><tr><td colspan="10" align="right"><b>JUMLAH TOTAL</b></td><td colspan="3"><b>'.$this->money($c['nilai_kontrak']??0).'</b></td></tr></table>';$pdf->SetFont($this->font,'',max(6,$this->size-2));$pdf->writeHTML($html,true,false,true,false,'');return$pdf->Output('','S');
    }
    private function attendance(array $d,array $c,array $setup):string
    {
        $pdf=$this->page($setup);$this->title($pdf,"Daftar Hadir\nKlarifikasi dan Negosiasi");$pdf->writeHTML($this->fields(array_merge($this->package($c),[['Hari/Tanggal',$this->date($d,$c)],['Tempat',$this->v($this->user,'nama_opd').' - '.$this->v($this->user,'alamat_opd')]])).'<table cellpadding="2"><tr><td><b>PEJABAT PENGADAAN BARANG/JASA</b></td></tr></table><table border="1" cellpadding="6"><tr><th width="8%">No.</th><th width="42%">Nama</th><th width="25%">Jabatan</th><th width="25%">Tanda Tangan</th></tr><tr><td>1</td><td>'.$this->e($this->v($this->user,'nama_pejabat_pengadaan','nama_user')).'</td><td>Pejabat Pengadaan</td><td></td></tr></table><br><table cellpadding="2"><tr><td><b>PENYEDIA BARANG/JASA</b></td></tr></table><table border="1" cellpadding="6"><tr><th width="8%">No.</th><th width="42%">Nama</th><th width="25%">Jabatan</th><th width="25%">Tanda Tangan</th></tr><tr><td>1</td><td>'.$this->e($this->v($c,'direktur')).'</td><td>Direktur</td><td></td></tr></table>',true,false,true,false,'');return$pdf->Output('','S');
    }
    private function providerDecision(array $d,array $c,array $setup):string
    {
        $pdf=$this->page($setup);$this->title($pdf,'Penetapan Penyedia Jasa',$d['nomor_dokumen']??'');$this->para($pdf,'Berdasarkan Berita Acara Hasil Pengadaan Langsung tanggal '.$this->date($d,$c).', Pejabat Pengadaan Barang/Jasa menetapkan Penyedia Pengadaan Langsung untuk paket berikut:',5);$pdf->writeHTML($this->fields($this->package($c)).'<br><b>Adalah sebagai berikut:</b>'.$this->fields($this->provider($c)).'<br>Demikian Penetapan Penyedia ini dibuat untuk dipergunakan sebagaimana mestinya.',true,false,true,false,'');$this->signature($pdf,"Ditetapkan di Pasangkayu, ".$this->date($d,$c)."\nPejabat Pengadaan Barang/Jasa",$this->v($this->user,'nama_pejabat_pengadaan','nama_user'),$this->v($this->user,'nip_pejabat_pengadaan','nip'));return$pdf->Output('','S');
    }
    private function announcement(array $d,array $c,array $setup):string
    {
        $pdf=$this->page($setup);$this->title($pdf,'Pengumuman Penyedia Jasa',$d['nomor_dokumen']??'');$this->para($pdf,'Berdasarkan Surat Penetapan Penyedia, dengan ini diumumkan bahwa pelaksana Pengadaan Langsung untuk paket berikut:',5);$pdf->writeHTML($this->fields(array_slice($this->package($c),0,2)).'<br><b>Adalah sebagai berikut:</b>'.$this->fields($this->provider($c)).'<br>Demikian Pengumuman Penyedia ini dibuat untuk diketahui.',true,false,true,false,'');$this->signature($pdf,"Diumumkan di Pasangkayu, ".$this->date($d,$c)."\nPejabat Pengadaan Barang/Jasa",$this->v($this->user,'nama_pejabat_pengadaan','nama_user'),$this->v($this->user,'nip_pejabat_pengadaan','nip'));return$pdf->Output('','S');
    }
    private function evaluation(array $d,array $c,array $setup,bool $final):string
    {
        $pdf=$this->page($setup);$this->title($pdf,$final?"Berita Acara\nHasil Pemilihan":"Berita Acara\nHasil Evaluasi Penawaran",$d['nomor_dokumen']??'');$pdf->SetFont($this->font,'',$final?max(6.25,$this->size-2.35):max(7,$this->size-1.5));
        $this->para($pdf,'Pada hari dan tanggal '.$this->date($d,$c).' telah dibuat '.($final?'Berita Acara Hasil Pemilihan':'Berita Acara Hasil Evaluasi Penawaran').' untuk paket pekerjaan berikut:',$final?4.2:5);
        $provider=$this->e($this->v($c,'nama_penyedia_resmi','nama_penyedia'));$address=$this->e($this->v($c,'alamat_penyedia','alamat'));$price=$this->money($c['nilai_kontrak']??0);
        $html=$this->fields([['Kode Paket',$this->v($c,'kode_paket','kd_sub_keg')],['Nama Paket',$this->v($c,'uraian_kontrak')],['Nilai Total HPS',$price],['Sumber Dana',$this->v($c,'sumber_dana')],['Metode Evaluasi','Pengadaan Langsung']]);
        $html.='<p><b>Dengan hasil sebagai berikut:</b></p><p><b>A. Pembukaan Penawaran</b><br>Dari 1 (satu) peserta yang mendaftar terdapat 1 (satu) peserta yang memasukkan dokumen penawaran, yaitu:</p><table border="1" cellpadding="4"><tr><th width="8%">No.</th><th width="32%">Nama Peserta</th><th width="40%">Alamat Peserta</th><th width="20%">Nilai Penawaran</th></tr><tr><td>1</td><td>'.$provider.'</td><td>'.$address.'</td><td>'.$price.'</td></tr></table>';
        foreach(['Evaluasi Administrasi','Evaluasi Teknis','Evaluasi Harga'] as $i=>$stage){$html.='<p><b>'.($i+1).'. '.$stage.'</b></p><table border="1" cellpadding="'.($final?'3':'4').'"><tr><th width="8%">No.</th><th width="'.($i===2?'32':'42').'%">Nama Peserta</th>'.($i===2?'<th width="22%">Penawaran</th>':'').'<th width="'.($i===2?'18':'25').'%">Hasil Evaluasi</th><th width="'.($i===2?'20':'25').'%">Keterangan</th></tr><tr><td>1</td><td>'.$provider.'</td>'.($i===2?'<td>'.$price.'</td>':'').'<td>LULUS</td><td></td></tr></table>';}
        if($final)$html.='<p><b>3. Hasil Negosiasi Biaya sebagai berikut:</b></p>'.$this->fields([['Nama Penyedia',$this->v($c,'nama_penyedia_resmi','nama_penyedia')],['Nilai Penawaran',$price],['Nilai Penawaran Terkoreksi',$price],['Nilai Negosiasi Biaya',$price]]);
        $html.='<p>Demikian berita acara dibuat dan ditandatangani pada hari, tanggal, dan bulan sebagaimana tersebut di atas untuk dipergunakan sebagaimana mestinya.</p>';$pdf->writeHTML($html,true,false,true,false,'');$this->signature($pdf,'Pejabat Pengadaan Barang/Jasa',$this->v($this->user,'nama_pejabat_pengadaan','nama_user'),$this->v($this->user,'nip_pejabat_pengadaan','nip'));return$pdf->Output('','S');
    }
    private function sppbj(array $d,array $c,array $setup):string
    {
        $pdf=$this->page($setup);$pdf->writeHTML('<table><tr><td width="60%">Nomor &nbsp;&nbsp;&nbsp;: '.$this->e($d['nomor_dokumen']??'-').'<br>Lampiran : -</td><td width="40%">Pasangkayu, '.$this->e($this->date($d,$c)).'</td></tr></table><br><b>Kepada Yth.<br>Direktur '.$this->e($this->v($c,'nama_penyedia_resmi','nama_penyedia')).'<br>di-<br>'.$this->e($this->v($c,'alamat_penyedia','alamat')).'</b><br><br><b>Perihal: Penunjukan Penyedia untuk Pelaksanaan Paket Pekerjaan '.$this->e($this->v($c,'uraian_kontrak')).'</b><br><br>',true,false,true,false,'');$this->para($pdf,'Dengan ini kami beritahukan bahwa penawaran Saudara untuk pekerjaan '.$this->v($c,'uraian_kontrak').' dengan nilai hasil negosiasi '.$this->money($c['nilai_kontrak']??0).' dinyatakan diterima dan disetujui.',6);$this->para($pdf,'Sebagai tindak lanjut Surat Penunjukan Penyedia Barang/Jasa ini, Saudara diharuskan menandatangani Surat Perjanjian atau SPK paling lambat 14 (empat belas) hari kerja setelah diterbitkannya SPPBJ.',6);$this->para($pdf,'Penunjukan ini diberikan berdasarkan hasil evaluasi terhadap penawaran Saudara. Apabila Saudara tidak bersedia menerima penunjukan ini, akan dikenakan sanksi sesuai ketentuan pengadaan barang/jasa pemerintah yang berlaku.',6);$this->signature($pdf,'Pejabat Pembuat Komitmen',$this->v($c,'nama_ppk_resmi','nama_ppk'),$this->v($c,'nip_ppk_resmi','nip_ppk'));$pdf->writeHTML('<br><b>Tembusan Yth.:</b><ol><li>Kepala Daerah (sebagai laporan);</li><li>LPSE;</li><li>Pejabat Pengadaan.</li></ol>',true,false,true,false,'');return$pdf->Output('','S');
    }
    private function spmk(array $d,array $c,array $setup):string
    {
        $pdf=$this->page($setup);$this->title($pdf,'Surat Perintah Mulai Kerja (SPMK)',$d['nomor_dokumen']??'');$pdf->SetFont($this->font,'',$this->size);$pdf->MultiCell(0,5,'Tanggal : '.$this->date($d,$c),0,'C');$pdf->SetFont($this->font,'B',$this->size+1);$pdf->MultiCell(0,6,"PAKET PEKERJAAN:\n".$this->v($c,'uraian_kontrak'),0,'C');$pdf->SetFont($this->font,'',$this->size);
        $pdf->writeHTML('<p>Yang bertanda tangan di bawah ini:</p>'.$this->fields([['Nama',$this->v($c,'nama_ppk_resmi','nama_ppk')],['Jabatan','PPK '.$this->v($this->user,'nama_opd')],['Alamat',$this->v($this->user,'alamat_opd')]]).'<p>Selanjutnya disebut Pejabat Pembuat Komitmen;</p><p>berdasarkan Surat Perintah Kerja (SPK)</p>'.$this->fields([['Nomor',$c['nomor_kontrak']??'-'],['Tanggal',$this->date($d,$c)]]).'<p>Bersama ini memerintahkan:</p>'.$this->fields([['Nama Penyedia',$this->v($c,'nama_penyedia_resmi','nama_penyedia')],['Alamat',$this->v($c,'alamat_penyedia','alamat')],['yang dalam hal ini diwakili oleh',$this->v($c,'direktur')]]).'<p>Selanjutnya disebut sebagai Penyedia;</p><p>untuk segera memulai pelaksanaan pekerjaan dengan memperhatikan ketentuan-ketentuan sebagai berikut:</p>'.$this->fields([['1. Macam Pekerjaan',$this->v($c,'jenis_pengadaan').' '.$this->v($c,'nama_sub_kegiatan','nama_sub_keg','kd_sub_keg')],['2. Tanggal Mulai Kerja',$this->date($d,$c)],['3. Syarat-Syarat Pekerjaan','sesuai dengan persyaratan dan ketentuan Kontrak'],['4. Waktu Penyelesaian',$this->v($c,'waktu_pelaksanaan').' hari kalender dan pekerjaan harus selesai sesuai tanggal kontrak'],['5. Hasil Pekerjaan','1 (satu) paket '.$this->v($c,'uraian_kontrak').' sesuai Kerangka Acuan Kerja/Spesifikasi Teknis']]),true,false,true,false,'');
        $pdf->AddPage();$pdf->writeHTML($this->fields([['6. Denda','Terhadap keterlambatan penyerahan hasil kerja dan laporan akhir, pembayaran kepada Penyedia dapat dikenakan denda atau dihentikan sesuai ketentuan dalam SPK.']]),true,false,true,false,'');$pdf->writeHTML('<br><table><tr><td width="50%" align="center">Untuk dan atas nama<br>'.$this->e($this->v($this->user,'nama_opd')).'<br>Pejabat Pembuat Komitmen<br><br><br><b><u>'.$this->e($this->v($c,'nama_ppk_resmi','nama_ppk')).'</u></b><br>NIP. '.$this->e($this->v($c,'nip_ppk_resmi','nip_ppk')).'</td><td width="50%" align="center">Menerima dan Menyetujui<br>Untuk dan atas nama<br>'.$this->e($this->v($c,'nama_penyedia_resmi','nama_penyedia')).'<br><br><br><b><u>'.$this->e($this->v($c,'direktur')).'</u></b><br>Direktur</td></tr></table>',true,false,true,false,'');return$pdf->Output('','S');
    }
    private function preContract(array $d,array $c,array $setup):string
    {
        $pdf=$this->page($setup);$this->title($pdf,"Berita Acara Rapat Persiapan\nPenandatanganan SPK dan Pelaksanaan Pekerjaan",$d['nomor_dokumen']??'');
        $this->para($pdf,'Pada tanggal '.$this->date($d,$c).', Pejabat Pembuat Komitmen pada '.$this->v($this->user,'nama_opd').' mengadakan Rapat Persiapan Penandatanganan Kontrak dan Persiapan Pelaksanaan Pekerjaan (Pre Award Meeting/Pre Construction) untuk pengadaan berikut:',5);
        $pdf->writeHTML($this->fields(array_merge($this->package($c),[['Penyedia Jasa',$this->v($c,'nama_penyedia_resmi','nama_penyedia')],['Alamat',$this->v($c,'alamat_penyedia','alamat')]])).'<p>Pelaksanaan dan hasil rapat persiapan penandatanganan kontrak dan persiapan pelaksanaan pekerjaan menghasilkan hal-hal pokok berikut:</p><ol><li>Rapat dipimpin oleh '.$this->e($this->v($c,'nama_ppk_resmi','nama_ppk')).' selaku PPK dan dihadiri oleh unsur Pengguna Anggaran/PPK, Penyedia Jasa/Rekanan, PPTK/Tim Teknis, serta Konsultan Supervisi/Pengawasan apabila ada.</li><li>Rapat dimulai pada waktu yang disepakati para pihak.</li><li>Nilai Kontrak termasuk Pajak Pertambahan Nilai berdasarkan total harga penawaran terkoreksi adalah '.$this->money($c['nilai_kontrak']??0).'.</li><li>Hasil pembahasan secara lengkap tercantum dalam lampiran.</li><li>Berita acara ini beserta lampirannya merupakan bagian dari dokumen kontrak.</li></ol><p>Demikian Berita Acara ini dibuat dengan sebenar-benarnya untuk dipergunakan sebagaimana mestinya.</p><table><tr><td width="50%" align="center">Menyetujui Penyedia Barang/Jasa<br>'.$this->e($this->v($c,'nama_penyedia_resmi','nama_penyedia')).'<br><br><br><b><u>'.$this->e($this->v($c,'direktur')).'</u></b><br>Direktur</td><td width="50%" align="center">Untuk dan atas nama<br>'.$this->e($this->v($this->user,'nama_opd')).'<br>Pejabat Pembuat Komitmen<br><br><br><b><u>'.$this->e($this->v($c,'nama_ppk_resmi','nama_ppk')).'</u></b><br>NIP. '.$this->e($this->v($c,'nip_ppk_resmi','nip_ppk')).'</td></tr></table>',true,false,true,false,'');
        $pdf->AddPage();$pdf->SetFont($this->font,'',$this->size);$pdf->writeHTML($this->fields([['Lampiran','Berita Acara Rapat Persiapan Penandatanganan SPK dan Persiapan Pelaksanaan Pekerjaan'],['Nomor',$d['nomor_dokumen']??'-'],['Tanggal',$this->date($d,$c)],['Pekerjaan',$this->v($c,'uraian_kontrak')]]),true,false,true,false,'');
        $agreements=['Nilai kontrak termasuk pajak adalah '.$this->money($c['nilai_kontrak']??0).'.','Harga satuan pekerjaan sesuai hasil koreksi aritmatik atau hasil negosiasi dan bersifat tetap sesuai bentuk kontrak.','Syarat-syarat umum SPK adalah tetap.','Kerangka Acuan Kerja/Spesifikasi Teknis adalah tetap.','Berita Acara Rapat Persiapan ini merupakan bagian dari Dokumen Kontrak.'];$html='<table border="1" cellpadding="5"><tr style="font-weight:bold"><th width="8%">No.</th><th width="72%">KESEPAKATAN</th><th width="20%">PERNYATAAN PENYEDIA JASA</th></tr>';foreach($agreements as $i=>$agreement)$html.='<tr><td>'.($i+1).'</td><td>'.$this->e($agreement).'</td><td align="center">Setuju</td></tr>';$html.='</table><br><table border="1" cellpadding="6"><tr style="font-weight:bold"><th width="8%">No.</th><th width="42%">NAMA</th><th width="28%">JABATAN</th><th width="22%">TANDA TANGAN</th></tr><tr><td>1</td><td>'.$this->e($this->v($c,'nama_ppk_resmi','nama_ppk')).'<br>NIP. '.$this->e($this->v($c,'nip_ppk_resmi','nip_ppk')).'</td><td>Pengguna Jasa/Pejabat Pembuat Komitmen</td><td></td></tr><tr><td>2</td><td>'.$this->e($this->v($c,'direktur')).'</td><td>Direktur '.$this->e($this->v($c,'nama_penyedia_resmi','nama_penyedia')).'</td><td></td></tr><tr><td>3</td><td>-</td><td>PPTK/Tim Teknis</td><td></td></tr></table>';$pdf->writeHTML($html,true,false,true,false,'');return$pdf->Output('','S');
    }
}
