START TRANSACTION;
SET @w='76.01',@o='1.03.0.00.0.00.01.0000',@y=2026,@u='TRACE_TEST_PHASE4';
SET @sub1=(SELECT id FROM rekening_kegiatan WHERE kode='X.XX.1.2.01.1' LIMIT 1),@sub2=(SELECT id FROM rekening_kegiatan WHERE kode='X.XX.1.2.01.2' LIMIT 1);
SET @satuan=(SELECT id FROM satuan_neo WHERE is_deleted=0 ORDER BY id LIMIT 1),@dana=(SELECT id FROM sumber_dana_neo WHERE is_deleted=0 ORDER BY id LIMIT 1),@akun=(SELECT kode FROM akun_neo WHERE kode='5.1.02.02.05.0044' LIMIT 1);
SET @renstra_sub=(SELECT id FROM sub_kegiatan_renstra_neo WHERE keterangan='TRACE_TEST Phase 3' AND is_deleted=0 LIMIT 1);

INSERT INTO rekanan_neo(kd_wilayah,nama_perusahaan,alamat,email,npwp,no_rekening,bank_rekening,atas_nama_rekening,direktur,jabatan,keterangan,username_insert,is_deleted)
SELECT @w,'TRACE_TEST PT Infrastruktur Maju','Pasangkayu','paket-a@example.test','00.000.000.0-000.001','001001','Bank Sulbar','PT Infrastruktur Maju','Andi Pratama','Direktur','TRACE_TEST Phase 4',@u,0 WHERE NOT EXISTS(SELECT 1 FROM rekanan_neo WHERE npwp='00.000.000.0-000.001' AND is_deleted=0);
INSERT INTO rekanan_neo(kd_wilayah,nama_perusahaan,alamat,email,npwp,no_rekening,bank_rekening,atas_nama_rekening,direktur,jabatan,keterangan,username_insert,is_deleted)
SELECT @w,'TRACE_TEST CV Karya Mandiri','Mamuju Tengah','paket-b@example.test','00.000.000.0-000.002','002002','Bank Sulbar','CV Karya Mandiri','Siti Rahma','Direktur','TRACE_TEST Phase 4',@u,0 WHERE NOT EXISTS(SELECT 1 FROM rekanan_neo WHERE npwp='00.000.000.0-000.002' AND is_deleted=0);
SET @rek1=(SELECT id FROM rekanan_neo WHERE npwp='00.000.000.0-000.001' AND is_deleted=0 LIMIT 1),@rek2=(SELECT id FROM rekanan_neo WHERE npwp='00.000.000.0-000.002' AND is_deleted=0 LIMIT 1);

INSERT INTO rkpd_neo(renstra_sub_kegiatan_id,kd_wilayah,kd_opd,tahun,kd_program,kd_kegiatan,kd_sub_keg,indikator,target,satuan_id,pagu,sumber_dana_id,lokasi,kelompok_sasaran,status,kunci,setujui,keterangan,tgl_insert,username_insert)
SELECT @renstra_sub,@w,@o,@y,'X.XX.1','X.XX.1.2.01','X.XX.1.2.01.1','TRACE_TEST Phase 4 Paket A: dokumen perencanaan',1,@satuan,240000000,@dana,'Pasangkayu','Perangkat Daerah','approved',1,1,'TRACE_TEST Phase 4 Paket A',NOW(),@u WHERE NOT EXISTS(SELECT 1 FROM rkpd_neo WHERE keterangan='TRACE_TEST Phase 4 Paket A' AND is_deleted=0);
INSERT INTO rkpd_neo(renstra_sub_kegiatan_id,kd_wilayah,kd_opd,tahun,kd_program,kd_kegiatan,kd_sub_keg,indikator,target,satuan_id,pagu,sumber_dana_id,lokasi,kelompok_sasaran,status,kunci,setujui,keterangan,tgl_insert,username_insert)
SELECT @renstra_sub,@w,@o,@y,'X.XX.1','X.XX.1.2.01','X.XX.1.2.01.2','TRACE_TEST Phase 4 Paket B: dokumen RKA',1,@satuan,180000000,@dana,'Pasangkayu','Perangkat Daerah','approved',1,1,'TRACE_TEST Phase 4 Paket B',NOW(),@u WHERE NOT EXISTS(SELECT 1 FROM rkpd_neo WHERE keterangan='TRACE_TEST Phase 4 Paket B' AND is_deleted=0);
SET @rk1=(SELECT id FROM rkpd_neo WHERE keterangan='TRACE_TEST Phase 4 Paket A' AND is_deleted=0 LIMIT 1),@rk2=(SELECT id FROM rkpd_neo WHERE keterangan='TRACE_TEST Phase 4 Paket B' AND is_deleted=0 LIMIT 1);

INSERT INTO renja_neo(source_table,source_id,kd_wilayah,kd_opd,tahun,kd_sub_keg,kd_akun,uraian,harga_satuan,volume,jumlah,sumber_dana_id,kunci,setujui,keterangan,tgl_insert,username_insert)
SELECT 'rkpd_neo',@rk1,@w,@o,@y,'X.XX.1.2.01.1',@akun,'TRACE_TEST Phase 4 Paket A',240000000,1,240000000,@dana,1,1,'TRACE_TEST Phase 4 Paket A',NOW(),@u WHERE NOT EXISTS(SELECT 1 FROM renja_neo WHERE source_table='rkpd_neo' AND source_id=@rk1 AND is_deleted=0);
INSERT INTO renja_neo(source_table,source_id,kd_wilayah,kd_opd,tahun,kd_sub_keg,kd_akun,uraian,harga_satuan,volume,jumlah,sumber_dana_id,kunci,setujui,keterangan,tgl_insert,username_insert)
SELECT 'rkpd_neo',@rk2,@w,@o,@y,'X.XX.1.2.01.2',@akun,'TRACE_TEST Phase 4 Paket B',180000000,1,180000000,@dana,1,1,'TRACE_TEST Phase 4 Paket B',NOW(),@u WHERE NOT EXISTS(SELECT 1 FROM renja_neo WHERE source_table='rkpd_neo' AND source_id=@rk2 AND is_deleted=0);
SET @rn1=(SELECT id FROM renja_neo WHERE source_table='rkpd_neo' AND source_id=@rk1 AND is_deleted=0 LIMIT 1),@rn2=(SELECT id FROM renja_neo WHERE source_table='rkpd_neo' AND source_id=@rk2 AND is_deleted=0 LIMIT 1);
INSERT INTO rka_neo(source_table,source_id,kd_wilayah,kd_opd,tahun,kd_sub_keg,kd_akun,uraian,harga_satuan,volume,jumlah,sumber_dana_id,kunci,setujui,keterangan,tgl_insert,username_insert) SELECT 'renja_neo',@rn1,@w,@o,@y,'X.XX.1.2.01.1',@akun,'TRACE_TEST Phase 4 Paket A',240000000,1,240000000,@dana,1,1,'TRACE_TEST Phase 4 Paket A',NOW(),@u WHERE NOT EXISTS(SELECT 1 FROM rka_neo WHERE source_table='renja_neo' AND source_id=@rn1 AND is_deleted=0);
INSERT INTO rka_neo(source_table,source_id,kd_wilayah,kd_opd,tahun,kd_sub_keg,kd_akun,uraian,harga_satuan,volume,jumlah,sumber_dana_id,kunci,setujui,keterangan,tgl_insert,username_insert) SELECT 'renja_neo',@rn2,@w,@o,@y,'X.XX.1.2.01.2',@akun,'TRACE_TEST Phase 4 Paket B',180000000,1,180000000,@dana,1,1,'TRACE_TEST Phase 4 Paket B',NOW(),@u WHERE NOT EXISTS(SELECT 1 FROM rka_neo WHERE source_table='renja_neo' AND source_id=@rn2 AND is_deleted=0);
SET @ra1=(SELECT id FROM rka_neo WHERE source_table='renja_neo' AND source_id=@rn1 AND is_deleted=0 LIMIT 1),@ra2=(SELECT id FROM rka_neo WHERE source_table='renja_neo' AND source_id=@rn2 AND is_deleted=0 LIMIT 1);
INSERT INTO dpa_neo(source_table,source_id,kd_wilayah,kd_opd,tahun,kd_sub_keg,kd_akun,uraian,harga_satuan,volume,jumlah,sumber_dana_id,kunci,setujui,keterangan,tgl_insert,username_insert) SELECT 'rka_neo',@ra1,@w,@o,@y,'X.XX.1.2.01.1',@akun,'TRACE_TEST Phase 4 Paket A',240000000,1,240000000,@dana,1,1,'TRACE_TEST Phase 4 Paket A',NOW(),@u WHERE NOT EXISTS(SELECT 1 FROM dpa_neo WHERE source_table='rka_neo' AND source_id=@ra1 AND is_deleted=0);
INSERT INTO dpa_neo(source_table,source_id,kd_wilayah,kd_opd,tahun,kd_sub_keg,kd_akun,uraian,harga_satuan,volume,jumlah,sumber_dana_id,kunci,setujui,keterangan,tgl_insert,username_insert) SELECT 'rka_neo',@ra2,@w,@o,@y,'X.XX.1.2.01.2',@akun,'TRACE_TEST Phase 4 Paket B',180000000,1,180000000,@dana,1,1,'TRACE_TEST Phase 4 Paket B',NOW(),@u WHERE NOT EXISTS(SELECT 1 FROM dpa_neo WHERE source_table='rka_neo' AND source_id=@ra2 AND is_deleted=0);
SET @dp1=(SELECT id FROM dpa_neo WHERE source_table='rka_neo' AND source_id=@ra1 AND is_deleted=0 LIMIT 1),@dp2=(SELECT id FROM dpa_neo WHERE source_table='rka_neo' AND source_id=@ra2 AND is_deleted=0 LIMIT 1);

INSERT INTO rkpd_p_neo(source_rkpd_id,renstra_sub_kegiatan_id,kd_wilayah,kd_opd,tahun,kd_program,kd_kegiatan,kd_sub_keg,indikator,target_awal,pagu_awal,target,satuan_id,pagu,sumber_dana_id,status_perubahan,status,kunci,setujui,keterangan,tgl_insert,username_insert)
SELECT @rk1,@renstra_sub,@w,@o,@y,'X.XX.1','X.XX.1.2.01','X.XX.1.2.01.1','TRACE_TEST Phase 4 Paket A Perubahan',1,240000000,1,@satuan,250000000,@dana,'ubah','approved',1,1,'TRACE_TEST Phase 4 Paket A',NOW(),@u WHERE NOT EXISTS(SELECT 1 FROM rkpd_p_neo WHERE source_rkpd_id=@rk1 AND is_deleted=0);
INSERT INTO rkpd_p_neo(source_rkpd_id,renstra_sub_kegiatan_id,kd_wilayah,kd_opd,tahun,kd_program,kd_kegiatan,kd_sub_keg,indikator,target_awal,pagu_awal,target,satuan_id,pagu,sumber_dana_id,status_perubahan,status,kunci,setujui,keterangan,tgl_insert,username_insert)
SELECT @rk2,@renstra_sub,@w,@o,@y,'X.XX.1','X.XX.1.2.01','X.XX.1.2.01.2','TRACE_TEST Phase 4 Paket B Perubahan',1,180000000,1,@satuan,190000000,@dana,'ubah','approved',1,1,'TRACE_TEST Phase 4 Paket B',NOW(),@u WHERE NOT EXISTS(SELECT 1 FROM rkpd_p_neo WHERE source_rkpd_id=@rk2 AND is_deleted=0);
INSERT INTO renja_p_neo(source_table,source_id,kd_wilayah,kd_opd,tahun,kd_sub_keg,kd_akun,uraian,jumlah_awal,jumlah,sumber_dana_id,status_perubahan,kunci,setujui,keterangan,tgl_insert,username_insert) SELECT 'renja_neo',@rn1,@w,@o,@y,'X.XX.1.2.01.1',@akun,'TRACE_TEST Phase 4 Paket A',240000000,250000000,@dana,'ubah',1,1,'TRACE_TEST Phase 4 Paket A',NOW(),@u WHERE NOT EXISTS(SELECT 1 FROM renja_p_neo WHERE source_table='renja_neo' AND source_id=@rn1 AND is_deleted=0);
INSERT INTO renja_p_neo(source_table,source_id,kd_wilayah,kd_opd,tahun,kd_sub_keg,kd_akun,uraian,jumlah_awal,jumlah,sumber_dana_id,status_perubahan,kunci,setujui,keterangan,tgl_insert,username_insert) SELECT 'renja_neo',@rn2,@w,@o,@y,'X.XX.1.2.01.2',@akun,'TRACE_TEST Phase 4 Paket B',180000000,190000000,@dana,'ubah',1,1,'TRACE_TEST Phase 4 Paket B',NOW(),@u WHERE NOT EXISTS(SELECT 1 FROM renja_p_neo WHERE source_table='renja_neo' AND source_id=@rn2 AND is_deleted=0);
INSERT INTO rka_p_neo(source_table,source_id,kd_wilayah,kd_opd,tahun,kd_sub_keg,kd_akun,uraian,jumlah_awal,jumlah,sumber_dana_id,status_perubahan,kunci,setujui,keterangan,tgl_insert,username_insert) SELECT 'rka_neo',@ra1,@w,@o,@y,'X.XX.1.2.01.1',@akun,'TRACE_TEST Phase 4 Paket A',240000000,250000000,@dana,'ubah',1,1,'TRACE_TEST Phase 4 Paket A',NOW(),@u WHERE NOT EXISTS(SELECT 1 FROM rka_p_neo WHERE source_table='rka_neo' AND source_id=@ra1 AND is_deleted=0);
INSERT INTO rka_p_neo(source_table,source_id,kd_wilayah,kd_opd,tahun,kd_sub_keg,kd_akun,uraian,jumlah_awal,jumlah,sumber_dana_id,status_perubahan,kunci,setujui,keterangan,tgl_insert,username_insert) SELECT 'rka_neo',@ra2,@w,@o,@y,'X.XX.1.2.01.2',@akun,'TRACE_TEST Phase 4 Paket B',180000000,190000000,@dana,'ubah',1,1,'TRACE_TEST Phase 4 Paket B',NOW(),@u WHERE NOT EXISTS(SELECT 1 FROM rka_p_neo WHERE source_table='rka_neo' AND source_id=@ra2 AND is_deleted=0);
INSERT INTO dppa_neo(source_table,source_id,kd_wilayah,kd_opd,tahun,kd_sub_keg,kd_akun,uraian,jumlah_awal,jumlah,sumber_dana_id,status_perubahan,kunci,setujui,keterangan,tgl_insert,username_insert) SELECT 'dpa_neo',@dp1,@w,@o,@y,'X.XX.1.2.01.1',@akun,'TRACE_TEST Phase 4 Paket A',240000000,250000000,@dana,'ubah',1,1,'TRACE_TEST Phase 4 Paket A',NOW(),@u WHERE NOT EXISTS(SELECT 1 FROM dppa_neo WHERE source_table='dpa_neo' AND source_id=@dp1 AND is_deleted=0);
INSERT INTO dppa_neo(source_table,source_id,kd_wilayah,kd_opd,tahun,kd_sub_keg,kd_akun,uraian,jumlah_awal,jumlah,sumber_dana_id,status_perubahan,kunci,setujui,keterangan,tgl_insert,username_insert) SELECT 'dpa_neo',@dp2,@w,@o,@y,'X.XX.1.2.01.2',@akun,'TRACE_TEST Phase 4 Paket B',180000000,190000000,@dana,'ubah',1,1,'TRACE_TEST Phase 4 Paket B',NOW(),@u WHERE NOT EXISTS(SELECT 1 FROM dppa_neo WHERE source_table='dpa_neo' AND source_id=@dp2 AND is_deleted=0);
SET @dpp2=(SELECT id FROM dppa_neo WHERE source_table='dpa_neo' AND source_id=@dp2 AND is_deleted=0 LIMIT 1);

INSERT INTO daftar_paket_neo(kd_rup,kd_paket,kd_wilayah,kd_opd,tahun,sumber_tahap,anggaran_id,uraian,id_uraian,kd_sub_keg,volume,satuan,harga_satuan,jumlah,pagu,metode_pengadaan,metode_pemilihan,pengadaan_penyedia,jns_kontrak,id_rekanan,nama_rekanan,nama_ppk,waktu_pelaksanaan,tgl_kontrak,no_kontrak,tgl_spmk,no_spmk,username_insert,keterangan,setujui,kunci,is_deleted)
SELECT 'RUP-P4-A','PAKET-P4-A',@w,@o,@y,'dpa',@dp1,'TRACE_TEST Paket A dari DPA','[]','X.XX.1.2.01.1',1,'Paket',225000000,225000000,240000000,'Pengadaan Barang/Jasa','Tender','Penyedia','Harga Satuan',@rek1,'TRACE_TEST PT Infrastruktur Maju','PPK TRACE TEST',120,'2026-02-01','KONTRAK/P4/A','2026-02-05','SPMK/P4/A',@u,'TRACE_TEST Phase 4 Paket A',1,1,0 WHERE NOT EXISTS(SELECT 1 FROM daftar_paket_neo WHERE kd_paket='PAKET-P4-A' AND is_deleted=0);
INSERT INTO daftar_paket_neo(kd_rup,kd_paket,kd_wilayah,kd_opd,tahun,sumber_tahap,anggaran_id,uraian,id_uraian,kd_sub_keg,volume,satuan,harga_satuan,jumlah,pagu,metode_pengadaan,metode_pemilihan,pengadaan_penyedia,jns_kontrak,id_rekanan,nama_rekanan,nama_ppk,waktu_pelaksanaan,tgl_kontrak,no_kontrak,tgl_spmk,no_spmk,username_insert,keterangan,setujui,kunci,is_deleted)
SELECT 'RUP-P4-B','PAKET-P4-B',@w,@o,@y,'dppa',@dpp2,'TRACE_TEST Paket B dari DPPA','[]','X.XX.1.2.01.2',1,'Paket',175000000,175000000,190000000,'Pengadaan Langsung','Pengadaan Langsung','Penyedia','Lumsum',@rek2,'TRACE_TEST CV Karya Mandiri','PPK TRACE TEST',90,'2026-03-01','KONTRAK/P4/B','2026-03-05','SPMK/P4/B',@u,'TRACE_TEST Phase 4 Paket B',1,1,0 WHERE NOT EXISTS(SELECT 1 FROM daftar_paket_neo WHERE kd_paket='PAKET-P4-B' AND is_deleted=0);
SET @p1=(SELECT id FROM daftar_paket_neo WHERE kd_paket='PAKET-P4-A' AND is_deleted=0 LIMIT 1),@p2=(SELECT id FROM daftar_paket_neo WHERE kd_paket='PAKET-P4-B' AND is_deleted=0 LIMIT 1);
INSERT INTO kontrak_neo(kd_wilayah,kd_opd,tahun,kd_sub_keg,anggaran_id,paket_id,rekanan_id,nama_sub_keg,tahap,total_anggaran,nilai_kontrak,nomor_spk,tanggal_spk,nomor_kontrak,tanggal_kontrak,uraian_kontrak,nomor_spmk,tanggal_spmk,waktu_pelaksanaan,tanggal_mulai,tanggal_selesai,nama_ppk,nama_penyedia,status_kontrak,setujui,kunci,is_deleted,keterangan,tgl_insert,username_insert)
SELECT @w,@o,@y,'X.XX.1.2.01.1',@dp1,@p1,@rek1,'Penyusunan Dokumen Perencanaan','dpa',240000000,225000000,'SPK/P4/A','2026-02-01','KONTRAK/P4/A','2026-02-01','TRACE_TEST Paket A dari DPA','SPMK/P4/A','2026-02-05',120,'2026-02-05','2026-06-04','PPK TRACE TEST','TRACE_TEST PT Infrastruktur Maju','berjalan',1,1,0,'TRACE_TEST Phase 4 Paket A',NOW(),@u WHERE NOT EXISTS(SELECT 1 FROM kontrak_neo WHERE nomor_kontrak='KONTRAK/P4/A' AND is_deleted=0);
INSERT INTO kontrak_neo(kd_wilayah,kd_opd,tahun,kd_sub_keg,anggaran_id,paket_id,rekanan_id,nama_sub_keg,tahap,total_anggaran,nilai_kontrak,nomor_spk,tanggal_spk,nomor_kontrak,tanggal_kontrak,uraian_kontrak,nomor_spmk,tanggal_spmk,waktu_pelaksanaan,tanggal_mulai,tanggal_selesai,nama_ppk,nama_penyedia,status_kontrak,setujui,kunci,is_deleted,keterangan,tgl_insert,username_insert)
SELECT @w,@o,@y,'X.XX.1.2.01.2',@dpp2,@p2,@rek2,'Penyusunan Dokumen RKA','dppa',190000000,175000000,'SPK/P4/B','2026-03-01','KONTRAK/P4/B','2026-03-01','TRACE_TEST Paket B dari DPPA','SPMK/P4/B','2026-03-05',90,'2026-03-05','2026-06-03','PPK TRACE TEST','TRACE_TEST CV Karya Mandiri','selesai',1,1,0,'TRACE_TEST Phase 4 Paket B',NOW(),@u WHERE NOT EXISTS(SELECT 1 FROM kontrak_neo WHERE nomor_kontrak='KONTRAK/P4/B' AND is_deleted=0);
SET @k1=(SELECT id FROM kontrak_neo WHERE nomor_kontrak='KONTRAK/P4/A' AND is_deleted=0 LIMIT 1),@k2=(SELECT id FROM kontrak_neo WHERE nomor_kontrak='KONTRAK/P4/B' AND is_deleted=0 LIMIT 1);
INSERT INTO daftar_uraian_paket(id_paket,id_dok_anggaran,dok,tahun,kd_wilayah,kd_opd,kd_sub_keg,kd_akun,kel_rek,jumlah_pagu,jumlah_kontrak,vol_kontrak,sat_kontrak,realisasi_vol,realisasi_jumlah,keterangan,tgl_insert,username_insert)
SELECT @p1,@dp1,'dpa',@y,@w,@o,'X.XX.1.2.01.1',@akun,'Belanja',240000000,225000000,1,'Paket',0,0,'TRACE_TEST Phase 4 Paket A',NOW(),@u WHERE NOT EXISTS(SELECT 1 FROM daftar_uraian_paket WHERE id_paket=@p1 AND id_dok_anggaran=@dp1);
INSERT INTO daftar_uraian_paket(id_paket,id_dok_anggaran,dok,tahun,kd_wilayah,kd_opd,kd_sub_keg,kd_akun,kel_rek,jumlah_pagu,jumlah_kontrak,vol_kontrak,sat_kontrak,realisasi_vol,realisasi_jumlah,keterangan,tgl_insert,username_insert)
SELECT @p2,@dpp2,'dppa',@y,@w,@o,'X.XX.1.2.01.2',@akun,'Belanja',190000000,175000000,1,'Paket',0,0,'TRACE_TEST Phase 4 Paket B',NOW(),@u WHERE NOT EXISTS(SELECT 1 FROM daftar_uraian_paket WHERE id_paket=@p2 AND id_dok_anggaran=@dpp2);
SET @up1=(SELECT id FROM daftar_uraian_paket WHERE id_paket=@p1 AND id_dok_anggaran=@dp1 LIMIT 1),@up2=(SELECT id FROM daftar_uraian_paket WHERE id_paket=@p2 AND id_dok_anggaran=@dpp2 LIMIT 1);
INSERT INTO daftar_realisasi_neo(tahun,kd_wilayah,kd_opd,kd_sub_keg,kd_akun,id_paket,kontrak_id,ket_paket,id_uraian_paket,ket_uraian_paket,id_dok_anggaran,dok,vol,jumlah,tanggal,periode,progress_fisik,nomor_bukti,username_insert,keterangan,setujui,kunci,is_deleted)
SELECT @y,@w,@o,'X.XX.1.2.01.1',@akun,@p1,@k1,'TRACE_TEST Paket A',@up1,'Termin I',@dp1,'dpa',0.35,78750000,'2026-03-31',3,35,'BUKTI/P4/A/1',@u,'TRACE_TEST Phase 4 Paket A Termin I',1,1,0 WHERE NOT EXISTS(SELECT 1 FROM daftar_realisasi_neo WHERE nomor_bukti='BUKTI/P4/A/1' AND is_deleted=0);
INSERT INTO daftar_realisasi_neo(tahun,kd_wilayah,kd_opd,kd_sub_keg,kd_akun,id_paket,kontrak_id,ket_paket,id_uraian_paket,ket_uraian_paket,id_dok_anggaran,dok,vol,jumlah,tanggal,periode,progress_fisik,nomor_bukti,username_insert,keterangan,setujui,kunci,is_deleted)
SELECT @y,@w,@o,'X.XX.1.2.01.1',@akun,@p1,@k1,'TRACE_TEST Paket A',@up1,'Termin II',@dp1,'dpa',0.30,67500000,'2026-04-30',4,65,'BUKTI/P4/A/2',@u,'TRACE_TEST Phase 4 Paket A Termin II',1,1,0 WHERE NOT EXISTS(SELECT 1 FROM daftar_realisasi_neo WHERE nomor_bukti='BUKTI/P4/A/2' AND is_deleted=0);
INSERT INTO daftar_realisasi_neo(tahun,kd_wilayah,kd_opd,kd_sub_keg,kd_akun,id_paket,kontrak_id,ket_paket,id_uraian_paket,ket_uraian_paket,id_dok_anggaran,dok,vol,jumlah,tanggal,periode,progress_fisik,nomor_bukti,username_insert,keterangan,setujui,kunci,is_deleted)
SELECT @y,@w,@o,'X.XX.1.2.01.2',@akun,@p2,@k2,'TRACE_TEST Paket B',@up2,'Termin I',@dpp2,'dppa',0.50,87500000,'2026-04-15',4,50,'BUKTI/P4/B/1',@u,'TRACE_TEST Phase 4 Paket B Termin I',1,1,0 WHERE NOT EXISTS(SELECT 1 FROM daftar_realisasi_neo WHERE nomor_bukti='BUKTI/P4/B/1' AND is_deleted=0);
INSERT INTO daftar_realisasi_neo(tahun,kd_wilayah,kd_opd,kd_sub_keg,kd_akun,id_paket,kontrak_id,ket_paket,id_uraian_paket,ket_uraian_paket,id_dok_anggaran,dok,vol,jumlah,tanggal,periode,progress_fisik,nomor_bukti,username_insert,keterangan,setujui,kunci,is_deleted)
SELECT @y,@w,@o,'X.XX.1.2.01.2',@akun,@p2,@k2,'TRACE_TEST Paket B',@up2,'Termin II',@dpp2,'dppa',0.50,87500000,'2026-05-31',5,100,'BUKTI/P4/B/2',@u,'TRACE_TEST Phase 4 Paket B Termin II',1,1,0 WHERE NOT EXISTS(SELECT 1 FROM daftar_realisasi_neo WHERE nomor_bukti='BUKTI/P4/B/2' AND is_deleted=0);
COMMIT;
