<?php
require_once __DIR__.'/../app/Core/DB.php';
require_once __DIR__.'/../app/Services/KontrakRealisasiService.php';
require_once __DIR__.'/../app/Services/DynamicTableService.php';
$db=DB::getInstance(); $ok=static function($value,$message){if(!$value){fwrite(STDERR,"FAIL: $message\n");exit(1);}echo "PASS: $message\n";};
$ok((int)$db->query("SELECT COUNT(*) n FROM rkpd_neo WHERE keterangan IN ('TRACE_TEST Phase 4 Paket A','TRACE_TEST Phase 4 Paket B') AND is_deleted=0")->fetch()['n']===2,'dua data RKPD Phase 4 tersedia');
foreach(['renja_neo','rka_neo','dpa_neo','rkpd_p_neo','renja_p_neo','rka_p_neo','dppa_neo'] as $table)$ok((int)$db->query("SELECT COUNT(*) n FROM `$table` WHERE keterangan IN ('TRACE_TEST Phase 4 Paket A','TRACE_TEST Phase 4 Paket B') AND is_deleted=0")->fetch()['n']===2,"$table mempunyai dua rantai data");
$ok((int)$db->query("SELECT COUNT(*) n FROM rekanan_neo WHERE keterangan='TRACE_TEST Phase 4' AND is_deleted=0")->fetch()['n']===2,'dua penyedia berasal dari referensi');
$ok((int)$db->query("SELECT COUNT(*) n FROM kontrak_neo k JOIN rekanan_neo r ON r.id=k.rekanan_id WHERE k.keterangan LIKE 'TRACE_TEST Phase 4 Paket%' AND k.is_deleted=0")->fetch()['n']===2,'dua kontrak terhubung penyedia');
$ok((int)$db->query("SELECT COUNT(*) n FROM kontrak_neo WHERE keterangan LIKE 'TRACE_TEST Phase 4 Paket%' AND nomor_spk IS NOT NULL AND nomor_spmk IS NOT NULL AND is_deleted=0")->fetch()['n']===2,'SPK dan SPMK terisi');
$over=(int)$db->query("SELECT COUNT(*) n FROM kontrak_neo k JOIN (SELECT kontrak_id,SUM(jumlah) total FROM daftar_realisasi_neo WHERE is_deleted=0 GROUP BY kontrak_id) r ON r.kontrak_id=k.id WHERE r.total>k.nilai_kontrak AND k.keterangan LIKE 'TRACE_TEST Phase 4 Paket%'")->fetch()['n'];$ok($over===0,'realisasi tidak melebihi nilai kontrak');
$guarded=false;$sample=$db->query("SELECT * FROM daftar_realisasi_neo WHERE nomor_bukti='BUKTI/P4/A/1' LIMIT 1")->fetch();unset($sample['id']);$sample['jumlah']=9999999999;$sample['nomor_bukti']='TRACE_TEST_OVER_LIMIT';$db->begin();try{$db->insert('daftar_realisasi_neo',$sample);}catch(Throwable $e){$guarded=true;}$db->rollback();$ok($guarded,'database menolak realisasi melebihi kontrak');
$user=['kd_wilayah'=>'76.01','kd_opd'=>'1.03.0.00.0.00.01.0000','tahun'=>2026,'type_user'=>'super_admin'];$service=new KontrakRealisasiService($user);$summary=$service->summary();$ok((int)$summary['totals']['jumlah_kontrak']>=2,'summary grafik membaca kontrak');$ok(count($summary['monthly'])===12,'grafik mempunyai 12 bulan');
$_SESSION['user']=$user+['username'=>'phase4_test'];$dynamic=new DynamicTableService();$contractList=json_decode($dynamic->handle(['action'=>'list','tbl'=>'kontrak','req'=>'kontrak_dpa','cari'=>'TRACE_TEST','halaman'=>1,'rows'=>10]),true);$ok(($contractList['success']??false)&&count($contractList['data']??[])>=1,'subtab Kontrak DPA READ/SEARCH bekerja');$realizationList=json_decode($dynamic->handle(['action'=>'list','tbl'=>'realisasi','cari'=>'TRACE_TEST','halaman'=>1,'rows'=>10]),true);$ok(($realizationList['success']??false)&&count($realizationList['data']??[])>=4,'subtab Realisasi READ/SEARCH bekerja');$export=json_decode($dynamic->handle(['action'=>'export','tbl'=>'realisasi']),true);$ok(($export['success']??false),'export Excel realisasi melalui engine berjalan');
$id=(int)$db->query("SELECT id FROM kontrak_neo WHERE nomor_kontrak='KONTRAK/P4/A' LIMIT 1")->fetch()['id'];$ok(str_starts_with($service->contractPdf($id),'%PDF'),'PDF kontrak valid');$ok(str_starts_with($service->reportPdf(),'%PDF'),'PDF laporan valid');$xlsx=$service->reportExcel();$ok(is_file($xlsx)&&filesize($xlsx)>1000,'Excel laporan dengan grafik valid');unlink($xlsx);
echo "PHASE 4 TESTS COMPLETE\n";
