<?php
require_once __DIR__.'/../app/Core/DB.php';
require_once __DIR__.'/../app/Services/KontrakRealisasiService.php';
$db=DB::getInstance();$contract=$db->query('SELECT * FROM kontrak_neo WHERE is_deleted=0 AND nilai_kontrak>0 ORDER BY id LIMIT 1')->fetch();if(!$contract)throw new RuntimeException('Kontrak uji tidak tersedia');
$user=['kd_wilayah'=>$contract['kd_wilayah'],'kd_opd'=>$contract['kd_opd'],'tahun'=>$contract['tahun'],'username'=>'TRACE_PHASE10','type_user'=>'admin_opd'];$s=new KontrakRealisasiService($user);$assert=function($ok,$msg){if(!$ok)throw new RuntimeException('FAIL: '.$msg);echo "PASS: $msg\n";};
foreach(['kontrak_jadwal_neo','kontrak_dokumen_neo','user_subkegiatan_neo','kop_surat_neo','absensi_pegawai_neo','dokumen_pegawai_neo'] as $t)$assert((bool)$db->query('SELECT 1 FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name=?',[$t])->fetch(),"tabel $t tersedia");
$subs=$s->availableSubActivities((int)$contract['id']);$assert(count($subs)>0,'filter sub kegiatan kontrak tersedia');$items=$s->availableItems('',(int)$contract['id'],(string)$subs[0]['kd_sub_keg'],20);$assert(count($items)<=20,'hasil AJAX uraian dibatasi');
$rab=$s->saveRab((int)$contract['id'],[['nomor'=>'1','uraian'=>'Mobilisasi dan persiapan','satuan'=>'ls','volume'=>1,'harga_satuan'=>(float)$contract['nilai_kontrak']*.25],['nomor'=>'2','uraian'=>'Pekerjaan utama','satuan'=>'ls','volume'=>1,'harga_satuan'=>(float)$contract['nilai_kontrak']*.75]]);$assert(abs($rab['total']-(float)$contract['nilai_kontrak'])<1,'total RAB menyatu dengan nilai kontrak');
$schedule=$s->saveSchedule((int)$contract['id'],[['minggu_ke'=>1,'tanggal_mulai'=>$contract['tanggal_mulai']?:date('Y-m-d'),'tanggal_selesai'=>$contract['tanggal_mulai']?:date('Y-m-d'),'bobot_rencana'=>40,'bobot_realisasi'=>35],['minggu_ke'=>2,'tanggal_mulai'=>$contract['tanggal_mulai']?:date('Y-m-d'),'tanggal_selesai'=>$contract['tanggal_selesai']?:date('Y-m-d'),'bobot_rencana'=>60,'bobot_realisasi'=>55]]);$assert(count($schedule)===2 && (float)$schedule[1]['rencana_kumulatif']===100.0,'Kurva S menghitung kumulatif 100 persen');
$file=$s->rabExcel((int)$contract['id']);$assert(is_file($file)&&filesize($file)>1000,'Excel RAB dan Kurva S valid');unlink($file);$assert(str_starts_with($s->financialPdf('lra'),'%PDF'),'PDF LRA valid');$f=$s->financialExcel('spj');$assert(is_file($f)&&filesize($f)>1000,'Excel SPJ bendahara valid');unlink($f);echo "PHASE 10 TESTS COMPLETE\n";
