<?php
require_once __DIR__.'/../app/Core/DB.php';require_once __DIR__.'/../app/Services/AnggaranDocumentService.php';
$ok=static function($v,$m){if(!$v)throw new RuntimeException('FAIL: '.$m);echo"PASS: $m\n";};
$engine=file_get_contents(__DIR__.'/../public/assets/js/engine/form-engine.js');$profile=file_get_contents(__DIR__.'/../public/assets/js/modules/profil.js');$controller=file_get_contents(__DIR__.'/../app/Controllers/ProfilController.php');
$ok(str_contains($engine,'inferValidationSchema')&&str_contains($engine,'ui.success.message'),'semua form CRUD memiliki validasi inferensi dan feedback sukses di dalam form');
$ok(str_contains($profile,'/profil/upload-photo')&&str_contains($controller,'FILEINFO_MIME_TYPE'),'foto profil memakai upload tervalidasi dan pembaruan kartu langsung');
$ok(str_contains($profile,'/profil/periods')&&str_contains($controller,"'RPJMD':'RENSTRA'"),'periode tahun membedakan RPJMD daerah dan Renstra OPD');
$db=DB::getInstance();$scope=$db->query('SELECT kd_wilayah,kd_opd,tahun FROM dpa_neo WHERE is_deleted=0 ORDER BY id LIMIT 1')->fetch();$ok((bool)$scope,'scope anggaran tersedia');$service=new AnggaranDocumentService($scope+['username'=>'PHASE34','type_user'=>'admin_opd']);
foreach(['dpa'=>false,'dppa'=>true]as$logical=>$change){$file=$service->exportExcel($logical);$book=PhpOffice\PhpSpreadsheet\IOFactory::load($file);$sheet=$book->getSheet(0);$foundHierarchy=false;$detailWithoutCode=false;$foundPpn=false;foreach($sheet->getRowIterator()as$row){$a=(string)$sheet->getCell('A'.$row->getRowIndex())->getValue();$b=(string)$sheet->getCell('B'.$row->getRowIndex())->getValue();if(preg_match('/^5(?:\.|$)/',$a)&&$b!=='')$foundHierarchy=true;if($a===''&&$b!==''&&!str_contains($b,'JUMLAH'))$detailWithoutCode=true;foreach($row->getCellIterator()as$cell)if((string)$cell->getValue()==='PPN')$foundPpn=true;}$ok($foundHierarchy,"Excel $logical memuat hierarki nomor rekening dan uraian");$ok($detailWithoutCode,"Excel $logical tidak mengulang kode pada baris komponen");$ok($foundPpn,"Excel $logical menyamai kolom PPN PDF resmi");unlink($file);}echo"PHASE 34 VALIDATION/PROFILE/PERIOD/EXCEL TESTS COMPLETE\n";
