<div class="ui container" id="strukturOrganisasi" data-manage="<?= $canManage ? '1':'0' ?>">
  <div class="ui blue icon message"><i class="sitemap icon"></i><div class="content"><div class="header">Struktur Jabatan Struktural OPD</div><p>Susun jabatan dari Kepala OPD, Sekretaris/Kepala Bidang (Eselon III), hingga jabatan struktural terbawah. Pejabat hanya dapat dipilih dari Data ASN aktif OPD dan tahun berjalan.</p></div></div>
  <?php if($canManage): ?><button class="ui primary button" id="tambahJabatan"><i class="plus icon"></i>Tambah Jabatan</button><?php else: ?><div class="ui label">Mode baca — pengaturan dilakukan akun Kepala OPD/PA/KPA</div><?php endif; ?>
  <div class="ui divider"></div><div id="strukturList"><div class="ui active centered inline loader"></div></div>
</div>
<div class="ui modal" id="strukturModal"><i class="close icon"></i><div class="header">Atur Jabatan Struktural</div><div class="content"><form class="ui form" id="strukturForm"><input type="hidden" name="id"><div class="two fields"><div class="required field"><label>Nama Jabatan</label><input name="nama_jabatan" maxlength="255" list="jabatanAsn" required placeholder="Contoh: Kepala Dinas"></div><div class="required field"><label>Pejabat ASN</label><select class="ui fluid search dropdown" name="pegawai_id" required></select></div></div><div class="three fields"><div class="field"><label>Kelompok Jabatan</label><input name="kelompok_jabatan" maxlength="150" placeholder="Pimpinan Tinggi/Administrator/Pengawas"></div><div class="field"><label>Eselon</label><select class="ui dropdown" name="eselon"><option value="">Non-eselon</option><option>II.a</option><option>II.b</option><option>III.a</option><option>III.b</option><option>IV.a</option><option>IV.b</option></select></div><div class="field"><label>Urutan</label><input type="number" min="1" name="urutan" value="1"></div></div><div class="field"><label>Atasan Langsung</label><select class="ui fluid search dropdown" name="parent_id"><option value="">Tidak ada (pimpinan tertinggi)</option></select></div><div class="field"><label>Keterangan</label><textarea name="keterangan" rows="2" maxlength="500"></textarea></div><datalist id="jabatanAsn"></datalist></form></div><div class="actions"><button class="ui deny button">Batal</button><button class="ui primary button" id="simpanJabatan">Simpan</button></div></div>
<script>
(()=>{const root=$('#strukturOrganisasi'),canManage=Number(root.data('manage'))===1;let data={rows:[],employees:[]};const esc=s=>$('<div>').text(s??'').html();
function load(){Ajax.request({url:'/kepegawaian/struktur/data',method:'GET',success:r=>{if(!r?.success)return;data=r.data;render();fill();}})}
function fill(){const emp=$('#strukturForm [name="pegawai_id"]'),par=$('#strukturForm [name="parent_id"]');emp.html('<option value="">Pilih ASN</option>'+data.employees.map(x=>`<option value="${x.id}">${esc(x.nama)} — ${esc(x.nip||'-')} (${esc(x.jabatan||'tanpa jabatan')})</option>`).join(''));par.html('<option value="">Tidak ada (pimpinan tertinggi)</option>'+data.rows.map(x=>`<option value="${x.id}">${esc(x.nama_jabatan)} — ${esc(x.nama_pegawai||'-')}</option>`).join(''));$('#jabatanAsn').html([...new Set(data.employees.map(x=>x.jabatan).filter(Boolean))].map(x=>`<option value="${esc(x)}">`).join(''));$('.ui.dropdown').dropdown('refresh');}
function render(){if(!data.rows.length){$('#strukturList').html('<div class="ui placeholder segment"><div class="ui icon header"><i class="sitemap icon"></i>Belum ada struktur jabatan OPD</div></div>');return;}const byParent={};data.rows.forEach(x=>(byParent[x.parent_id||0]??=[]).push(x));const branch=(pid,depth=0)=>(byParent[pid]||[]).map(x=>`<div class="ui segment" style="margin-left:${Math.min(depth,5)*28}px;border-left:4px solid ${depth?'#21ba45':'#2185d0'}"><div class="ui right floated buttons">${canManage?`<button class="ui mini basic blue icon button edit-struktur" data-id="${x.id}"><i class="edit icon"></i></button><button class="ui mini basic red icon button hapus-struktur" data-id="${x.id}"><i class="trash icon"></i></button>`:''}</div><div class="ui ${depth?'teal':'blue'} label">${esc(x.eselon||'Non-eselon')}</div> <b>${esc(x.nama_jabatan)}</b><div class="ui small header" style="margin:8px 0 2px">${esc(x.nama_pegawai||'Belum ditetapkan')}</div><div class="meta">NIP ${esc(x.nip||'-')} · ${esc(x.kelompok_jabatan||'Kelompok belum diisi')}</div></div>${branch(x.id,depth+1)}`).join('');$('#strukturList').html(branch(0)+((byParent[0]||[]).length?'':'<div class="ui warning message">Semua jabatan memiliki atasan. Tetapkan satu jabatan sebagai pimpinan tertinggi.</div>'));}
$(document).off('.struktur').on('click.struktur','#tambahJabatan',()=>{$('#strukturForm')[0].reset();$('#strukturForm [name=id]').val('');fill();$('#strukturModal').modal('show')}).on('click.struktur','.edit-struktur',function(){const x=data.rows.find(r=>Number(r.id)===Number($(this).data('id')));if(!x)return;Object.entries(x).forEach(([k,v])=>$('#strukturForm [name="'+k+'"]').val(v??''));fill();Object.entries(x).forEach(([k,v])=>$('#strukturForm [name="'+k+'"]').val(v??'').trigger('change'));$('#strukturModal').modal('show')}).on('click.struktur','#simpanJabatan',()=>Ajax.request({url:'/kepegawaian/struktur/save',method:'POST',data:$('#strukturForm').serialize(),success:r=>{if(r?.success){$('#strukturModal').modal('hide');load();}}})).on('click.struktur','.hapus-struktur',function(){if(!confirm('Hapus jabatan ini dari struktur?'))return;Ajax.request({url:'/kepegawaian/struktur/delete',method:'POST',data:{id:$(this).data('id')},success:r=>{if(r?.success)load();}})});load();})();
</script>
