<?php
$role=(string)($_SESSION['user']['type_user']??'viewer');
$regional=in_array($role,['super_admin','admin_wilayah'],true);
$manager=in_array($role,['super_admin','admin_wilayah','admin_opd','kepala_opd'],true);
$group=static function(string $title,string $icon,array $items):void{?><div class="item"><div class="title"><i class="dropdown icon"></i> <i class="<?= $icon ?> icon"></i> <?= $title ?></div><div class="content"><?php foreach($items as [$label,$url,$page]): ?><a class="item" href="<?= $url ?>" data-spa="client" data-title="<?= $page ?>"><?= $label ?></a><?php endforeach; ?></div></div><?php };
?>
<div class="ui bottom attached segment pushable" id="mainContext"><div class="ui inverted vertical sidebar menu left sidebarutama ui accordion">
<div class="item"><h2 class="ui inverted header dash_header"><i class="circular blue building icon"></i><div class="content">seSendok<div class="sub header">Pemerintahan</div><div class="ui blue basic inverted label"><?= $_SESSION['user']['tahun']??date('Y') ?></div></div></h2></div>
<a class="item" href="/dashboard" data-spa="server" data-title="Dashboard"><i class="home icon"></i> Dashboard</a>
<?php $group('Referensi','database',[
 ['Urusan','/referensi?tbl=rekening_kegiatan&req=urusan','Referensi/Urusan'],['Bidang','/referensi?tbl=rekening_kegiatan&req=bidang','Referensi/Bidang'],['Program','/referensi?tbl=rekening_kegiatan&req=program','Referensi/Program'],['Kegiatan','/referensi?tbl=rekening_kegiatan&req=kegiatan','Referensi/Kegiatan'],['Sub Kegiatan','/referensi?tbl=rekening_kegiatan&req=sub_kegiatan','Referensi/Sub Kegiatan'],['Rekanan','/referensi?tbl=rekanan','Referensi/Rekanan'],['Satuan','/referensi?tbl=satuan','Referensi/Satuan'],['Mapping Biaya Akun','/mapping','Referensi/Mapping'],['Neraca','/referensi?tbl=aset','Referensi/Neraca'],['Akun','/referensi?tbl=akun','Referensi/Akun'],['Sumber Dana','/referensi?tbl=sumber_dana','Referensi/Sumber Dana'],['Organisasi OPD','/referensi?tbl=organisasi','Referensi/OPD'],['Peraturan','/referensi?tbl=peraturan','Referensi/Peraturan'],['Wilayah','/referensi?tbl=wilayah','Referensi/Wilayah']]);
$group('Standar Harga','calculator',array_map(fn($x)=>[strtoupper($x),'/standar_harga?tbl='.$x,'Standar Harga/'.strtoupper($x)],['ssh','hspk','asb','sbu']));
$group('Usulan','lightbulb outline',[['Daftar Usulan','/referensi?tbl=usulan_pembangunan','Usulan/Daftar Usulan']]);
$group('Perencanaan','project diagram',[['RPJMD Kabupaten','/referensi?tbl=rpjmd_kabupaten','Perencanaan/RPJMD'],['RENSTRA','/renstra','Perencanaan/Renstra'],['RKPD','/rkpd','Perencanaan/RKPD'],['RENJA','/renja','Perencanaan/Renja']]);
$group('Penganggaran','shopping cart',[['RKA','/rka','Penganggaran/RKA'],['DPA','/dpa','Penganggaran/DPA'],['RKPD Perubahan','/rkpd_perubahan','Penganggaran/RKPD Perubahan'],['RENJA Perubahan','/renja_perubahan','Penganggaran/Renja Perubahan'],['RKA Perubahan','/rka_perubahan','Penganggaran/RKA Perubahan'],['DPPA','/dppa','Penganggaran/DPPA']]);
$group('Kontrak','file signature',[['Daftar Kontrak','/kontrak?tbl=kontrak','Kontrak/Daftar Kontrak']]);
$group('Realisasi','chart line',[['Dashboard Realisasi','/kontrak?tbl=__laporan','Realisasi/Dashboard'],['Penginputan','/kontrak?tbl=realisasi','Realisasi/Penginputan']]);
$group('SAKIP & Kinerja','bullseye',[['IKU OPD','/referensi?tbl=iku_opd','SAKIP/IKU OPD'],['Pohon Kinerja','/referensi?tbl=pohon_kinerja','SAKIP/Pohon Kinerja'],['Target Renja','/referensi?tbl=renja_kinerja','SAKIP/Target Renja'],['Perjanjian Kinerja','/referensi?tbl=perjanjian_kinerja','SAKIP/Perjanjian Kinerja'],['Indikator PK','/referensi?tbl=perjanjian_kinerja_detail','SAKIP/Indikator PK'],['Pengukuran Kinerja','/referensi?tbl=pengukuran_kinerja','SAKIP/Pengukuran'],['Evaluasi Renja','/referensi?tbl=evaluasi_renja','SAKIP/Evaluasi Renja'],['Evaluasi Renstra','/referensi?tbl=evaluasi_renstra','SAKIP/Evaluasi Renstra']]);
if($manager)$group('Kepegawaian','users',array_map(fn($x)=>[$x[1],'/kepegawaian?tbl='.$x[0],'Kepegawaian/'.$x[1]],[['asn','Data ASN'],['pppk','PPPK'],['riwayat_jabatan','Riwayat Jabatan'],['riwayat_pangkat','Riwayat Pangkat'],['cuti','Cuti & Izin'],['sk_pegawai','SK Pegawai'],['pejabat_tahunan','Pejabat Tahunan'],['absensi','Absensi'],['penugasan_subkegiatan','Role & Sub Kegiatan']]));
$group('Tata Naskah','file alternate',[['Dashboard','/tata_naskah/dokumen','Tata Naskah/Dashboard'],['Buat Naskah','/tata_naskah/buat','Tata Naskah/Buat'],['Daftar Naskah','/tata_naskah/daftar','Tata Naskah/Daftar'],['Kop Surat Resmi','/kop_surat','Tata Naskah/Kop Surat']]); ?>
<?php if($manager): ?><a class="item" href="/user_opd" data-spa="server" data-title="User & Role OPD"><i class="users cog icon"></i> User &amp; Role OPD</a><?php endif; ?>
<a class="item" href="/pengaturan" data-spa="client" data-title="Pengaturan"><i class="toolbox icon"></i> Pengaturan</a>
<?php if($manager): ?><a class="item" href="/halaman_berita" data-spa="client" data-title="Berita"><i class="newspaper icon"></i> Berita</a><?php endif; ?>
<?php if($role==='super_admin'): ?><a class="item" href="/reset_tabel" data-spa="client" data-title="Reset Tabel"><i class="erase icon"></i> Reset Tabel</a><a class="item" href="/user_pemda" data-spa="client" data-title="User Pemda"><i class="users icon"></i> User Pemda</a><?php endif; ?>
<a class="item" href="/wallchat" data-spa="server" data-title="Pesan"><i class="comments outline icon"></i> Pesan</a><a class="item" href="/profil" data-spa="server" data-title="Profil"><i class="user icon"></i> Profil</a>
</div>
