-- Struktur hierarki rincian belanja SIPD: [#] paket, [-] uraian kelompok,
-- sumber dana tekstual, dan koefisien sebagaimana tercetak pada dokumen.
ALTER TABLE renja_neo MODIFY kelompok VARCHAR(500) NULL, MODIFY sat_1 VARCHAR(100) NULL, MODIFY sat_2 VARCHAR(100) NULL, MODIFY sat_3 VARCHAR(100) NULL, MODIFY sat_4 VARCHAR(100) NULL, MODIFY sat_5 VARCHAR(100) NULL,
  ADD COLUMN sumber_dana_teks VARCHAR(500) NULL AFTER sumber_dana_id,
  ADD COLUMN koefisien_keterangan VARCHAR(500) NULL AFTER volume;
ALTER TABLE rka_neo MODIFY kelompok VARCHAR(500) NULL, MODIFY sat_1 VARCHAR(100) NULL, MODIFY sat_2 VARCHAR(100) NULL, MODIFY sat_3 VARCHAR(100) NULL, MODIFY sat_4 VARCHAR(100) NULL, MODIFY sat_5 VARCHAR(100) NULL,
  ADD COLUMN sumber_dana_teks VARCHAR(500) NULL AFTER sumber_dana_id,
  ADD COLUMN koefisien_keterangan VARCHAR(500) NULL AFTER volume;
ALTER TABLE dpa_neo MODIFY kelompok VARCHAR(500) NULL, MODIFY sat_1 VARCHAR(100) NULL, MODIFY sat_2 VARCHAR(100) NULL, MODIFY sat_3 VARCHAR(100) NULL, MODIFY sat_4 VARCHAR(100) NULL, MODIFY sat_5 VARCHAR(100) NULL,
  ADD COLUMN sumber_dana_teks VARCHAR(500) NULL AFTER sumber_dana_id,
  ADD COLUMN koefisien_keterangan VARCHAR(500) NULL AFTER volume;
ALTER TABLE renja_p_neo MODIFY kelompok VARCHAR(500) NULL, MODIFY sat_1 VARCHAR(100) NULL, MODIFY sat_2 VARCHAR(100) NULL, MODIFY sat_3 VARCHAR(100) NULL, MODIFY sat_4 VARCHAR(100) NULL, MODIFY sat_5 VARCHAR(100) NULL,
  ADD COLUMN sumber_dana_teks VARCHAR(500) NULL AFTER sumber_dana_id,
  ADD COLUMN koefisien_keterangan VARCHAR(500) NULL AFTER volume;
ALTER TABLE rka_p_neo MODIFY kelompok VARCHAR(500) NULL, MODIFY sat_1 VARCHAR(100) NULL, MODIFY sat_2 VARCHAR(100) NULL, MODIFY sat_3 VARCHAR(100) NULL, MODIFY sat_4 VARCHAR(100) NULL, MODIFY sat_5 VARCHAR(100) NULL,
  ADD COLUMN sumber_dana_teks VARCHAR(500) NULL AFTER sumber_dana_id,
  ADD COLUMN koefisien_keterangan VARCHAR(500) NULL AFTER volume;
ALTER TABLE dppa_neo MODIFY kelompok VARCHAR(500) NULL, MODIFY sat_1 VARCHAR(100) NULL, MODIFY sat_2 VARCHAR(100) NULL, MODIFY sat_3 VARCHAR(100) NULL, MODIFY sat_4 VARCHAR(100) NULL, MODIFY sat_5 VARCHAR(100) NULL,
  ADD COLUMN sumber_dana_teks VARCHAR(500) NULL AFTER sumber_dana_id,
  ADD COLUMN koefisien_keterangan VARCHAR(500) NULL AFTER volume;
