-- Idempotent repair for legacy budget classifications used by the edit flyout.
UPDATE renja_neo SET objek_belanja=CASE WHEN kd_akun LIKE '5.2.%' THEN 'belanja_modal' WHEN kd_akun LIKE '5.3.%' THEN 'belanja_tidak_terduga' ELSE 'belanja_operasi' END WHERE is_deleted=0 AND (objek_belanja IS NULL OR objek_belanja='');
UPDATE rka_neo SET objek_belanja=CASE WHEN kd_akun LIKE '5.2.%' THEN 'belanja_modal' WHEN kd_akun LIKE '5.3.%' THEN 'belanja_tidak_terduga' ELSE 'belanja_operasi' END WHERE is_deleted=0 AND (objek_belanja IS NULL OR objek_belanja='');
UPDATE dpa_neo SET objek_belanja=CASE WHEN kd_akun LIKE '5.2.%' THEN 'belanja_modal' WHEN kd_akun LIKE '5.3.%' THEN 'belanja_tidak_terduga' ELSE 'belanja_operasi' END WHERE is_deleted=0 AND (objek_belanja IS NULL OR objek_belanja='');
UPDATE renja_p_neo p LEFT JOIN renja_neo s ON s.id=p.source_id SET p.objek_belanja=COALESCE(NULLIF(s.objek_belanja,''),CASE WHEN p.kd_akun LIKE '5.2.%' THEN 'belanja_modal' WHEN p.kd_akun LIKE '5.3.%' THEN 'belanja_tidak_terduga' ELSE 'belanja_operasi' END),p.jenis_kelompok=COALESCE(NULLIF(s.jenis_kelompok,''),IF(COALESCE(p.kelompok,'')='','non_paket','pemaketan')),p.jenis_standar_harga=COALESCE(p.jenis_standar_harga,s.jenis_standar_harga),p.id_standar_harga=COALESCE(p.id_standar_harga,s.id_standar_harga) WHERE p.is_deleted=0;
UPDATE rka_p_neo p LEFT JOIN rka_neo s ON s.id=p.source_id SET p.objek_belanja=COALESCE(NULLIF(s.objek_belanja,''),CASE WHEN p.kd_akun LIKE '5.2.%' THEN 'belanja_modal' WHEN p.kd_akun LIKE '5.3.%' THEN 'belanja_tidak_terduga' ELSE 'belanja_operasi' END),p.jenis_kelompok=COALESCE(NULLIF(s.jenis_kelompok,''),IF(COALESCE(p.kelompok,'')='','non_paket','pemaketan')),p.jenis_standar_harga=COALESCE(p.jenis_standar_harga,s.jenis_standar_harga),p.id_standar_harga=COALESCE(p.id_standar_harga,s.id_standar_harga) WHERE p.is_deleted=0;
UPDATE dppa_neo p LEFT JOIN dpa_neo s ON s.id=p.source_id SET p.objek_belanja=COALESCE(NULLIF(s.objek_belanja,''),CASE WHEN p.kd_akun LIKE '5.2.%' THEN 'belanja_modal' WHEN p.kd_akun LIKE '5.3.%' THEN 'belanja_tidak_terduga' ELSE 'belanja_operasi' END),p.jenis_kelompok=COALESCE(NULLIF(s.jenis_kelompok,''),IF(COALESCE(p.kelompok,'')='','non_paket','pemaketan')),p.jenis_standar_harga=COALESCE(p.jenis_standar_harga,s.jenis_standar_harga),p.id_standar_harga=COALESCE(p.id_standar_harga,s.id_standar_harga) WHERE p.is_deleted=0;
UPDATE renja_neo SET jenis_kelompok=IF(COALESCE(kelompok,'')='','non_paket','pemaketan') WHERE is_deleted=0 AND (jenis_kelompok IS NULL OR jenis_kelompok='');
UPDATE rka_neo SET jenis_kelompok=IF(COALESCE(kelompok,'')='','non_paket','pemaketan') WHERE is_deleted=0 AND (jenis_kelompok IS NULL OR jenis_kelompok='');
UPDATE dpa_neo SET jenis_kelompok=IF(COALESCE(kelompok,'')='','non_paket','pemaketan') WHERE is_deleted=0 AND (jenis_kelompok IS NULL OR jenis_kelompok='');
