<div class="ui info message"><i class="landmark icon"></i>Kop aktif ini dipakai otomatis pada PDF kontrak dan dokumen pengadaan.</div>
<form class="ui form" id="officialLetterheadForm" enctype="multipart/form-data">
  <input type="hidden" name="id" value="<?= (int)($kop['id']??0) ?>">
  <div class="two fields"><div class="required field"><label>Nama Pemerintah</label><input name="nama_pemerintah" value="<?= htmlspecialchars($kop['nama_pemerintah']??'') ?>"></div><div class="required field"><label>Nama OPD</label><input name="nama_opd" value="<?= htmlspecialchars($kop['nama_opd']??'') ?>"></div></div>
  <div class="field"><label>Alamat</label><textarea name="alamat" rows="2"><?= htmlspecialchars($kop['alamat']??'') ?></textarea></div>
  <div class="four fields"><div class="field"><label>Telepon</label><input name="telepon" value="<?= htmlspecialchars($kop['telepon']??'') ?>"></div><div class="field"><label>Email</label><input type="email" name="email" value="<?= htmlspecialchars($kop['email']??'') ?>"></div><div class="field"><label>Website</label><input name="website" value="<?= htmlspecialchars($kop['website']??'') ?>"></div><div class="field"><label>Kode Pos</label><input name="kode_pos" value="<?= htmlspecialchars($kop['kode_pos']??'') ?>"></div></div>
  <div class="four fields"><div class="field"><label>Logo Kiri</label><input type="file" name="logo_kiri" accept="image/png,image/jpeg,image/webp"></div><div class="field"><label>Logo Kanan</label><input type="file" name="logo_kanan" accept="image/png,image/jpeg,image/webp"></div><div class="field"><label>Gambar Kop Penuh</label><input type="file" name="gambar_kop" accept="image/png,image/jpeg,image/webp"></div><div class="field"><label>Warna Garis</label><input type="color" name="warna_garis" value="<?= htmlspecialchars($kop['warna_garis']??'#000000') ?>"></div></div>
  <div class="two fields"><div class="field"><div class="ui toggle checkbox"><input type="checkbox" name="gunakan_gambar_kop" value="1" <?= !empty($kop['gunakan_gambar_kop'])?'checked':'' ?>><label>Gunakan gambar kop penuh</label></div></div><div class="field"><div class="ui toggle checkbox"><input type="checkbox" name="aktif" value="1" <?= !isset($kop['aktif'])||!empty($kop['aktif'])?'checked':'' ?>><label>Jadikan kop aktif</label></div></div></div>
  <button class="ui primary button" type="submit"><i class="save icon"></i>Simpan Kop Surat Resmi</button>
</form>
