<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli'){http_response_code(403);exit('CLI only');}
require_once __DIR__.'/../vendor/autoload.php';
$root=dirname(__DIR__);$excel=$argv[1]??$root.'/2024/Daftar Kontrak 2024.xlsx';$rabFile=$argv[2]??$root.'/2024/RAb Kontrak 2024.xlsx';
foreach([$excel,$rabFile] as $f)if(!is_file($f))throw new RuntimeException('File tidak ditemukan: '.$f);
$c=include $root.'/config/database.php';$pdo=new PDO(!empty($c['socket'])?'mysql:unix_socket='.$c['socket'].';dbname='.$c['dbname']:'mysql:host='.$c['host'].';dbname='.$c['dbname'],(string)$c['username'],(string)$c['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);$pdo->exec('SET NAMES utf8mb4 COLLATE utf8mb4_general_ci');
$w='76.01';$o='1.03.0.00.0.00.01.0000';$y=2024;$actor='IMPORT_KONTRAK_EXCEL_SUBKEG_2024';$norm=fn($v)=>mb_strtolower(trim(preg_replace('/\s+/u',' ',(string)$v)),'UTF-8');$num=fn($v)=>is_numeric($v)?(float)$v:null;
$date=function($v){if($v===null||trim((string)$v)==='')return null;if(is_numeric($v)&&(float)$v>20000)return PhpOffice\PhpSpreadsheet\Shared\Date::excelToDateTimeObject((float)$v)->format('Y-m-d');$v=trim((string)$v);return preg_match('/^\d{4}-\d{2}-\d{2}/',$v)?substr($v,0,10):null;};
$insert=function($table,$row)use($pdo){$cols=array_keys($row);$marks=implode(',',array_fill(0,count($cols),'?'));$pdo->prepare('INSERT INTO `'.$table.'` (`'.implode('`,`',$cols).'`) VALUES ('.$marks.')')->execute(array_values($row));return(int)$pdo->lastInsertId();};
$reader=PhpOffice\PhpSpreadsheet\IOFactory::createReaderForFile($excel);$reader->setReadDataOnly(true);$sheet=$reader->load($excel)->getActiveSheet();$contracts=[];
for($i=5;$i<=$sheet->getHighestRow();$i++){$no=trim((string)$sheet->getCell("B$i")->getValue());$value=$num($sheet->getCell("M$i")->getValue());if(!preg_match('/^\d{3,15}$/',$no)||$value===null||$value<=0)continue;$raw=preg_replace('/\s+/u','',trim((string)$sheet->getCell("AF$i")->getValue()));preg_match('~1\.03(?:\.\d+){4,5}~',$raw,$m);$code=$m[0]??'';if($code==='')continue;if(isset($contracts[$no]))throw new RuntimeException('Nomor kontrak ganda: '.$no);$contracts[$no]=['no'=>$no,'code'=>$code,'package'=>trim((string)$sheet->getCell("C$i")->getValue()),'budget'=>$num($sheet->getCell("J$i")->getValue())??0,'value'=>$value,'vendor'=>trim((string)$sheet->getCell("N$i")->getValue()),'director'=>trim((string)$sheet->getCell("O$i")->getValue()),'npwp'=>trim((string)$sheet->getCell("Q$i")->getValue()),'address'=>trim((string)$sheet->getCell("R$i")->getValue()),'contract_date'=>$date($sheet->getCell("AL$i")->getValue()),'spmk_date'=>$date($sheet->getCell("AM$i")->getValue()),'method'=>trim((string)$sheet->getCell("BI$i")->getValue()),'category'=>trim((string)$sheet->getCell("AE$i")->getValue()),'row'=>$i];}
$rr=PhpOffice\PhpSpreadsheet\IOFactory::createReaderForFile($rabFile);$rr->setReadDataOnly(true);$rb=$rr->load($rabFile);$rabs=[];foreach($rb->getWorksheetIterator() as $sh){$title=trim($sh->getTitle());if(!preg_match('/^(\d{3,15})/',$title,$m))continue;$no=$m[1];for($i=1;$i<=$sh->getHighestRow();$i++){$item=trim((string)$sh->getCell("A$i")->getValue());$desc=trim((string)$sh->getCell("B$i")->getValue());$vol=$num($sh->getCell("D$i")->getValue());$unit=trim((string)$sh->getCell("G$i")->getValue());$price=$num($sh->getCell("J$i")->getValue())??$num($sh->getCell("I$i")->getValue());if($desc===''||$vol===null||$vol<=0||$price===null||$price<0||$unit===''||!preg_match('/^\d+(?:\.\d+)?$/',$item))continue;$rabs[$no][]=['no'=>$item,'desc'=>$desc,'vol'=>$vol,'unit'=>$unit,'price'=>$price,'amount'=>$vol*$price,'row'=>$i];}}
$budget=[];$q=$pdo->prepare('SELECT id,kd_sub_keg,kd_akun,uraian,komponen,jumlah FROM dppa_neo WHERE kd_wilayah=? AND kd_opd=? AND tahun=? AND is_deleted=0 AND jumlah>0 ORDER BY id');$q->execute([$w,$o,$y]);foreach($q as $r)$budget[$r['kd_sub_keg']][]=$r;
foreach($contracts as $x)if(empty($budget[$x['code']]))throw new RuntimeException('DPPA tidak ditemukan untuk subkegiatan '.$x['code'].' kontrak '.$x['no']);
$existing=$pdo->prepare('SELECT COUNT(*) FROM kontrak_neo WHERE kd_wilayah=? AND kd_opd=? AND tahun=? AND is_deleted=0');$existing->execute([$w,$o,$y]);if((int)$existing->fetchColumn()>0)throw new RuntimeException('Kontrak aktif 2024 sudah ada.');
$pdo->beginTransaction();try{$vendorIds=[];$ids=[];$itemTotal=0;$rabTotal=0;foreach($budget as $rows){$marks=implode(',',array_fill(0,count($rows),'?'));$pdo->prepare("UPDATE dppa_neo SET setujui=1,kunci=1,tgl_update=NOW(),username_update=? WHERE id IN ($marks) AND is_deleted=0")->execute(array_merge([$actor],array_column($rows,'id')));}
foreach($contracts as$x){$vk=$norm($x['vendor']);if(!isset($vendorIds[$vk])){$vq=$pdo->prepare('SELECT id,nama_perusahaan FROM rekanan_neo WHERE kd_wilayah=? AND is_deleted=0');$vq->execute([$w]);$vid=null;foreach($vq as$v)if($norm($v['nama_perusahaan'])===$vk){$vid=(int)$v['id'];break;}if(!$vid)$vid=$insert('rekanan_neo',['kd_wilayah'=>$w,'nama_perusahaan'=>$x['vendor']?:'Tidak tercantum','alamat'=>$x['address']?:'-','npwp'=>$x['npwp']?:'-','direktur'=>$x['director']?:'-','disable'=>0,'is_deleted'=>0,'username_insert'=>$actor,'tgl_insert'=>date('Y-m-d H:i:s')]);$vendorIds[$vk]=$vid;}$rows=$budget[$x['code']];$pagu=array_sum(array_map(fn($r)=>(float)$r['jumlah'],$rows));$kind=str_contains(strtoupper($x['category']),'KONSULT')?'KONSULTANSI_KONSTRUKSI':(str_contains(strtoupper($x['category']),'BARANG')?'BARANG':'PEKERJAAN_KONSTRUKSI');$id=$insert('kontrak_neo',['kd_wilayah'=>$w,'kd_opd'=>$o,'tahun'=>$y,'kd_sub_keg'=>$x['code'],'anggaran_id'=>(int)$rows[0]['id'],'rekanan_id'=>$vendorIds[$vk],'nama_sub_keg'=>$x['code'],'tahap'=>'dppa','cara_pengadaan'=>'PENYEDIA','jenis_pengadaan'=>$kind,'metode_pemilihan'=>$x['method'],'bentuk_kontrak'=>'SURAT_PERJANJIAN','total_anggaran'=>$pagu,'nilai_hps'=>$x['budget'],'nilai_kontrak'=>$x['value'],'nomor_kontrak'=>'600/'.$x['no'],'tanggal_kontrak'=>$x['contract_date'],'tanggal_spmk'=>$x['spmk_date'],'uraian_kontrak'=>$x['package'],'nama_penyedia'=>$x['vendor'],'status_kontrak'=>'aktif','disable'=>0,'kunci'=>0,'setujui'=>0,'is_deleted'=>0,'keterangan'=>'Sumber Excel Daftar Kontrak 2024; mapping berdasarkan subkegiatan '.$x['code'].'; baris '.$x['row'],'tgl_insert'=>date('Y-m-d H:i:s'),'username_insert'=>$actor]);$ids[]=$id;$left=$x['value'];foreach($rows as$ix=>$r){$alloc=$ix===array_key_last($rows)?$left:round($x['value']*(float)$r['jumlah']/$pagu,2);$left-=$alloc;$insert('kontrak_item_neo',['kontrak_id'=>$id,'tahap'=>'dppa','anggaran_id'=>(int)$r['id'],'kd_wilayah'=>$w,'kd_opd'=>$o,'tahun'=>$y,'kd_sub_keg'=>$x['code'],'kd_akun'=>$r['kd_akun'],'uraian'=>$r['uraian'].' - '.($r['komponen']?:$x['package']),'pagu'=>$r['jumlah'],'nilai_kontrak'=>$alloc,'username_insert'=>$actor,'tgl_insert'=>date('Y-m-d H:i:s'),'is_deleted'=>0]);$itemTotal++;}foreach($rabs[$x['no']]??[] as$rab){$insert('rab_paket_neo',['kontrak_id'=>$id,'kontrak_item_id'=>null,'tahun'=>$y,'kd_wilayah'=>$w,'kd_opd'=>$o,'id_renja_p'=>0,'id_dpa'=>0,'id_dppa'=>(int)$rows[0]['id'],'nomor'=>$rab['no'],'uraian'=>$rab['desc'],'satuan'=>$rab['unit'],'type'=>'RAB Excel 2024','vol_hps'=>$rab['vol'],'vol_penawaran'=>$rab['vol'],'vol_negoisasi'=>$rab['vol'],'harga_sat_hps'=>$rab['price'],'harga_sat_penawaran'=>$rab['price'],'harga_sat_negoisasi'=>$rab['price'],'jumlah_hps'=>$rab['amount'],'jumlah_penawaran'=>$rab['amount'],'jumlah_negoisasi'=>$rab['amount'],'bobot'=>0,'keterangan'=>'Sheet '.$x['no'].' baris '.$rab['row'],'username_insert'=>$actor,'tgl_insert'=>date('Y-m-d H:i:s'),'is_deleted'=>0]);$rabTotal++;}}
$pdo->commit();echo json_encode(['contracts'=>count($ids),'contract_items'=>$itemTotal,'rab_rows'=>$rabTotal,'mapping'=>'subkegiatan DPPA'],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE).PHP_EOL;}catch(Throwable$e){$pdo->rollBack();throw$e;}
