<?php
/** Import transaksional kontrak, rekanan, tautan DPA, dan RAB PUPR 2026. */
if(PHP_SAPI!=='cli'){http_response_code(403);exit('CLI only');}
require_once __DIR__.'/../app/Core/DB.php';
$path=$argv[1]??'';if(!is_file($path))throw new RuntimeException('JSON ekstraksi kontrak tidak ditemukan');
$source=json_decode(file_get_contents($path),true,512,JSON_THROW_ON_ERROR);$scope=$source['scope']??[];
if(($scope['kd_wilayah']??'')!=='76.01'||($scope['kd_opd']??'')!=='1.03.0.00.0.00.01.0000'||(int)($scope['year']??0)!==2026)throw new RuntimeException('Scope sumber kontrak tidak sesuai');
$db=DB::getInstance();$username='IMPORT_KONTRAK_PUPR_2026';$w='76.01';$o='1.03.0.00.0.00.01.0000';$year=2026;
$norm=static fn($v)=>mb_strtolower(trim(preg_replace('/\s+/u',' ',str_replace(['stock','pemuktahiran'],['stok','pemutakhiran'],(string)$v))),'UTF-8');
$date=static fn($v)=>$v&&preg_match('/^\d{4}-\d{2}-\d{2}/',(string)$v,$m)?$m[0]:null;
$active=array_values(array_filter($source['contracts']??[],static fn($x)=>(float)($x['contract_value']??0)>0&&($x['vendor_excel_id']??0)>0&&trim((string)($x['contract_number']??''))!==''));
if(count($active)!==35)throw new RuntimeException('Jumlah kontrak riil bukan 35; import dibatalkan');

$vendorColumns=array_column($db->query('SHOW COLUMNS FROM rekanan_neo')->fetchAll(),'Field');if(!in_array('excel_source_id',$vendorColumns,true))$db->query('ALTER TABLE rekanan_neo ADD COLUMN excel_source_id INT NULL AFTER kd_wilayah');$vendorIndexes=array_column($db->query('SHOW INDEX FROM rekanan_neo')->fetchAll(),'Key_name');if(!in_array('uq_rekanan_excel_scope',$vendorIndexes,true))$db->query('ALTER TABLE rekanan_neo ADD UNIQUE INDEX uq_rekanan_excel_scope(kd_wilayah,excel_source_id)');

$dpa=$db->query('SELECT id,kd_sub_keg,kd_akun,kelompok,uraian,komponen,jumlah,source_id FROM dpa_neo WHERE kd_wilayah=? AND kd_opd=? AND tahun=? AND is_deleted=0 ORDER BY id',[$w,$o,$year])->fetchAll();
$byDescription=[];foreach($dpa as$row)$byDescription[$norm($row['uraian'])][]=$row;
$targets=static function(array$c)use($byDescription,$norm):array{
  $number=(string)$c['row_number'];
  if($number==='67314702'){ $found=[];foreach($byDescription as$key=>$rows)if(str_starts_with($key,$norm('Pembangunan Tangki Septik Skala Individual')))array_push($found,...$rows);return$found; }
  $names=$number==='02'?['Pemuktahiran Penguatan Database dan Survey Kondisi Jalan','Pemuktahiran Penguatan Database dan Survey Kondisi Jembatan']:
    ($number==='64449573'?['Peningkatan/Pemeliharaan rutin Jalan trans sulawesi - bambalamotu - sawi (DBH)']:[$c['package']]);
  $found=[];foreach($names as$name){$rows=$byDescription[$norm($name)]??[];array_push($found,...$rows);}return$found;
};
$mapped=[];foreach($active as$c){$rows=$targets($c);if(!$rows)throw new RuntimeException('Paket DPA tidak ditemukan untuk baris '.$c['row_number'].' '.$c['package']);$pagu=array_sum(array_map(static fn($r)=>(float)$r['jumlah'],$rows));if((float)$c['contract_value']>=$pagu)throw new RuntimeException('Nilai kontrak harus lebih kecil dari DPA untuk '.$c['row_number']);$mapped[$c['row_number']]=['contract'=>$c,'rows'=>$rows,'pagu'=>$pagu];}

$db->begin();
try{
  // Nonaktifkan seluruh rantai kontrak/RAB lama dalam scope yang diminta.
  $oldIds=array_column($db->query('SELECT id FROM kontrak_neo WHERE kd_wilayah=? AND kd_opd=? AND tahun=? AND is_deleted=0',[$w,$o,$year])->fetchAll(),'id');
  if($oldIds){$marks=implode(',',array_fill(0,count($oldIds),'?'));foreach(['rab_paket_neo','kontrak_item_neo','daftar_realisasi_neo','kontrak_jadwal_neo','kontrak_dokumen_neo']as$table)$db->query("UPDATE `$table` SET is_deleted=1 WHERE kontrak_id IN ($marks) AND is_deleted=0",$oldIds);$db->query("UPDATE kontrak_neo SET is_deleted=1,tgl_update=NOW(),username_update=? WHERE id IN ($marks)",[$username,...$oldIds]);}
  // Referensi rekanan mengikuti ID kolom No. pada workbook, tetapi nama disimpan tanpa awalan ID.
  $vendorDbIds=[];foreach($source['vendors']as$v){$excelId=(int)$v['excel_id'];$row=['kd_wilayah'=>$w,'excel_source_id'=>$excelId,'nama_perusahaan'=>$v['name'],'alamat'=>$v['address']?:'-','email'=>$v['email']?:null,'npwp'=>$v['npwp']?:'-','no_rekening'=>$v['bank_account']?:null,'atas_nama_rekening'=>$v['bank_account_name']?:$v['name'],'direktur'=>$v['director']?:'-','jabatan'=>$v['position']?:null,'no_ktp'=>$v['id_card']?:null,'no_akta_pendirian'=>$v['deed_number']?:null,'tgl_akta_pendirian'=>$date($v['deed_date']),'lokasi_notaris_pendirian'=>$v['deed_place']?:null,'nama_notaris_pendirian'=>$v['deed_notary']?:null,'no_akta_perubahan'=>$v['change_deed_number']?:null,'tgl_akta_perubahan'=>$date($v['change_deed_date']),'nama_notaris_perubahan'=>$v['change_deed_notary']?:null,'lokasi_notaris_perubahan'=>$v['change_deed_place']?:null,'keterangan'=>mb_substr($v['notes']?:$v['description'],0,255),'no_sortir'=>$v['sort'],'disable'=>0,'is_deleted'=>0,'username_update'=>$username,'tgl_update'=>date('Y-m-d H:i:s')];$existing=$db->query('SELECT id FROM rekanan_neo WHERE kd_wilayah=? AND (excel_source_id=? OR (excel_source_id IS NULL AND id=?)) ORDER BY excel_source_id IS NOT NULL DESC LIMIT 1',[$w,$excelId,$excelId])->fetch();if($existing){$dbId=(int)$existing['id'];$db->update('rekanan_neo',$row,'WHERE id=? AND kd_wilayah=?',[$dbId,$w]);}else{$row['username_insert']=$username;$row['tgl_insert']=date('Y-m-d H:i:s');unset($row['username_update'],$row['tgl_update']);$dbId=(int)$db->insert('rekanan_neo',$row);}$vendorDbIds[$excelId]=$dbId;}
  $db->query("UPDATE rekanan_neo SET is_deleted=1,tgl_update=NOW(),username_update=? WHERE kd_wilayah=? AND is_deleted=0 AND (UPPER(nama_perusahaan) LIKE 'DUMMY%' OR UPPER(COALESCE(keterangan,'')) LIKE '%DUMMY%' OR UPPER(nama_perusahaan) LIKE 'TRACE_TEST%')",[$username,$w]);

  $contractIds=[];$rabCount=0;$itemCount=0;
  foreach($mapped as$number=>$entry){$c=$entry['contract'];$rows=$entry['rows'];$first=$rows[0];foreach($rows as$r)$db->query('UPDATE dpa_neo SET setujui=1 WHERE id=?',[$r['id']]);$start=$date($c['spmk_date'])?:$date($c['contract_date']);$end=$start&&$c['duration_days']?date('Y-m-d',strtotime($start.' +'.max(0,(int)$c['duration_days']-1).' days')):null;$temporary=min((float)$c['contract_value'],(float)$first['jumlah']);
    $contractId=(int)$db->insert('kontrak_neo',['kd_wilayah'=>$w,'kd_opd'=>$o,'tahun'=>$year,'kd_sub_keg'=>$first['kd_sub_keg'],'anggaran_id'=>$first['id'],'rekanan_id'=>$vendorDbIds[(int)$c['vendor_excel_id']],'nama_sub_keg'=>$c['sub_activity_name'],'tahap'=>'dpa','total_anggaran'=>(float)$first['jumlah'],'nilai_kontrak'=>$temporary,'nomor_kontrak'=>$c['contract_number'],'tanggal_kontrak'=>$date($c['contract_date']),'uraian_kontrak'=>$c['package'],'nomor_spmk'=>$c['spmk_number'],'tanggal_spmk'=>$date($c['spmk_date']),'waktu_pelaksanaan'=>(int)$c['duration_days'],'tanggal_mulai'=>$start,'tanggal_selesai'=>$end,'nama_ppk'=>'','nama_penyedia'=>'','nama_tim_teknis'=>json_encode(array_values(array_filter([$c['technical_team']]))),'status_kontrak'=>'aktif','disable'=>0,'kunci'=>0,'setujui'=>0,'is_deleted'=>0,'keterangan'=>'Sumber Excel baris '.$c['excel_row'].'; nomor '.$number.'; '.$c['category'].'; '.$c['procurement_method'],'tgl_insert'=>date('Y-m-d H:i:s'),'username_insert'=>$username]);
    $left=(float)$c['contract_value'];$pagu=$entry['pagu'];$itemIds=[];foreach($rows as$index=>$r){$allocated=$index===array_key_last($rows)?$left:round((float)$c['contract_value']*(float)$r['jumlah']/$pagu,2);$left-=$allocated;$itemIds[]=(int)$db->insert('kontrak_item_neo',['kontrak_id'=>$contractId,'tahap'=>'dpa','anggaran_id'=>$r['id'],'kd_wilayah'=>$w,'kd_opd'=>$o,'tahun'=>$year,'kd_sub_keg'=>$r['kd_sub_keg'],'kd_akun'=>$r['kd_akun'],'uraian'=>$r['uraian'],'pagu'=>$r['jumlah'],'nilai_kontrak'=>$allocated,'tgl_insert'=>date('Y-m-d H:i:s'),'username_insert'=>$username,'is_deleted'=>0]);$itemCount++;}
    $db->update('kontrak_neo',['nilai_kontrak'=>(float)$c['contract_value'],'total_anggaran'=>$pagu,'tgl_update'=>date('Y-m-d H:i:s'),'username_update'=>$username],'WHERE id=?',[$contractId]);$contractIds[$number]=$contractId;
    if(isset($source['rabs'][$number])){$link=$db->query('SELECT d.id id_dpa,dp.id id_dppa,rp.id id_renja_p FROM dpa_neo d LEFT JOIN rka_neo rk ON rk.id=d.source_id LEFT JOIN renja_p_neo rp ON rp.source_id=rk.source_id AND rp.is_deleted=0 LEFT JOIN dppa_neo dp ON dp.source_table=? AND dp.source_id=d.id AND dp.is_deleted=0 WHERE d.id=? LIMIT 1',['dpa_neo',$first['id']])->fetch();$rabTotal=array_sum(array_map(static fn($x)=>(float)$x['amount_negotiated'],$source['rabs'][$number]['items']));foreach($source['rabs'][$number]['items']as$rab){$amount=(float)$rab['amount_negotiated'];$db->insert('rab_paket_neo',['kontrak_id'=>$contractId,'kontrak_item_id'=>$itemIds[0],'tahun'=>$year,'kd_wilayah'=>$w,'kd_opd'=>$o,'id_renja_p'=>(int)($link['id_renja_p']??0),'id_dpa'=>(int)$first['id'],'id_dppa'=>(int)($link['id_dppa']??0),'nomor'=>$rab['number'],'uraian'=>$rab['description'],'satuan'=>$rab['unit']?:'-','type'=>'RAB '.$source['rabs'][$number]['sheet'],'vol_hps'=>$rab['quantity_hps'],'vol_penawaran'=>$rab['quantity_offer'],'vol_negoisasi'=>$rab['quantity_negotiated'],'harga_sat_hps'=>$rab['unit_price_hps'],'harga_sat_penawaran'=>$rab['unit_price_offer'],'harga_sat_negoisasi'=>$rab['unit_price_negotiated'],'pajak'=>$rab['tax'],'jumlah_hps'=>$rab['amount_hps'],'jumlah_penawaran'=>$rab['amount_offer'],'jumlah_negoisasi'=>$amount,'bobot'=>$rabTotal?round($amount/$rabTotal*100,4):0,'keterangan'=>'Sheet '.$source['rabs'][$number]['sheet'].' baris '.$rab['excel_row'],'username_insert'=>$username,'tgl_insert'=>date('Y-m-d H:i:s'),'is_deleted'=>0]);$rabCount++;}}
  }
  $check=$db->query('SELECT COUNT(*) n,SUM(nilai_kontrak) nilai,SUM(total_anggaran) pagu,SUM(nilai_kontrak>=total_anggaran) tidak_valid FROM kontrak_neo WHERE kd_wilayah=? AND kd_opd=? AND tahun=? AND is_deleted=0',[$w,$o,$year])->fetch();if((int)$check['n']!==35||(int)$check['tidak_valid']!==0)throw new RuntimeException('Rekonsiliasi kontrak gagal');
  $db->commit();echo json_encode(['vendors'=>count($vendorDbIds),'contracts'=>(int)$check['n'],'contract_items'=>$itemCount,'rab_contracts'=>count($source['rabs']),'rab_rows'=>$rabCount,'contract_value'=>(float)$check['nilai'],'linked_dpa'=>(float)$check['pagu'],'contracts_without_rab'=>array_values(array_diff(array_keys($mapped),array_keys($source['rabs'])))],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE).PHP_EOL;
}catch(Throwable$e){$db->rollback();throw$e;}
