<?php
require_once __DIR__.'/../app/Core/DB.php';

$source=__DIR__.'/../tmp/pdfs/renstra-table.json';
if(!is_file($source))throw new RuntimeException('Hasil ekstraksi PDF tidak ditemukan.');
$rows=json_decode(file_get_contents($source),true,512,JSON_THROW_ON_ERROR);
$db=DB::getInstance();$wilayah='76.01';$opd='1.03.0.00.0.00.01.0000';$period=1;$actor='IMPORT_RENSTRA_PUPR_2025_2030';
$clean=static function(?string $v):string{$v=preg_replace('/\s+/u',' ',trim((string)$v));$v=preg_replace('/\s+KAB\. PASANGKAY U$/i','',$v);return trim($v," -\t\n\r\0\x0B");};
$number=static function($v):float{$v=trim((string)$v);if($v==='')return 0;return(float)str_replace(',','.',str_replace('.','',$v));};
$unit=static function(string $indicator):string{if(preg_match('/\(([^()]*)\)\s*$/u',$indicator,$m))return trim($m[1]);return str_contains($indicator,'%')?'%':'Dokumen';};
$unique=[];foreach($rows as $row)$unique[$row['code']]=$row;
$programs=array_filter($unique,fn($x)=>substr_count($x['code'],'.')===2);
$activities=array_filter($unique,fn($x)=>substr_count($x['code'],'.')===4);
$subs=array_filter($unique,fn($x)=>substr_count($x['code'],'.')===5);
if(count($programs)!==10||count($activities)!==23||count($subs)!==73)throw new RuntimeException('Struktur hasil ekstraksi tidak lengkap.');
$totals=[];foreach(range(2026,2030) as $y){$column=5+(($y-2026)*2);$totals[$y]=array_sum(array_map(fn($x)=>$number($x['row'][$column]??0),$subs));}

$db->begin();
try{
  $old=$db->query('SELECT id FROM renstra_neo WHERE kd_wilayah=? AND kd_opd=?',[$wilayah,$opd])->fetchAll();$renstraIds=array_map('intval',array_column($old,'id'));
  // Bersihkan seluruh rantai kontrak dummy lebih dahulu; trigger anggaran
  // sengaja menolak penghapusan DPA/DPPA yang masih dirujuk kontrak aktif.
  foreach(['kontrak_jadwal_neo','kontrak_dokumen_neo','daftar_realisasi_neo','rab_paket_neo','kontrak_item_neo'] as $table)$db->query("DELETE FROM `$table` WHERE kd_wilayah=? AND kd_opd=? AND tahun BETWEEN 2025 AND 2030",[$wilayah,$opd]);
  $db->query('DELETE FROM kontrak_neo WHERE kd_wilayah=? AND kd_opd=? AND tahun BETWEEN 2025 AND 2030',[$wilayah,$opd]);
  foreach(['pengukuran_kinerja_neo','perjanjian_kinerja_detail_neo','perjanjian_kinerja_neo','evaluasi_renstra_neo','pohon_kinerja_neo','iku_opd_neo','renja_sub_kegiatan_kinerja_neo','evaluasi_renja_neo'] as $table)$db->query("DELETE FROM `$table` WHERE kd_wilayah=? AND kd_opd=? AND ".($table==='iku_opd_neo'||$table==='evaluasi_renstra_neo'?'1=1':'tahun BETWEEN 2025 AND 2030'),[$wilayah,$opd]);
  foreach(['rkpd_neo','renja_neo','rka_neo','dpa_neo','rkpd_p_neo','renja_p_neo','rka_p_neo','dppa_neo'] as $table)$db->query("DELETE FROM `$table` WHERE kd_wilayah=? AND kd_opd=? AND tahun BETWEEN 2025 AND 2030",[$wilayah,$opd]);
  foreach($renstraIds as $rid){
    $mIds=array_column($db->query('SELECT id FROM misi_renstra_neo WHERE renstra_id=?',[$rid])->fetchAll(),'id');
    foreach($mIds as $mid){$tIds=array_column($db->query('SELECT id FROM tujuan_renstra_neo WHERE misi_id=?',[$mid])->fetchAll(),'id');foreach($tIds as $tid){$sIds=array_column($db->query('SELECT id FROM sasaran_renstra_neo WHERE tujuan_id=?',[$tid])->fetchAll(),'id');foreach($sIds as $sid){$pIds=array_column($db->query('SELECT id FROM program_renstra_neo WHERE sasaran_id=?',[$sid])->fetchAll(),'id');foreach($pIds as $pid){$kIds=array_column($db->query('SELECT id FROM kegiatan_renstra_neo WHERE program_id=?',[$pid])->fetchAll(),'id');foreach($kIds as $kid)$db->query('DELETE FROM sub_kegiatan_renstra_neo WHERE kegiatan_renstra_id=?',[$kid]);$db->query('DELETE FROM kegiatan_renstra_neo WHERE program_id=?',[$pid]);$db->query('DELETE FROM indikator_program_renstra_neo WHERE program_id=?',[$pid]);}$db->query('DELETE FROM program_renstra_neo WHERE sasaran_id=?',[$sid]);$db->query('DELETE FROM indikator_sasaran_renstra_neo WHERE sasaran_id=?',[$sid]);}$db->query('DELETE FROM sasaran_renstra_neo WHERE tujuan_id=?',[$tid]);}$db->query('DELETE FROM tujuan_renstra_neo WHERE misi_id=?',[$mid]);}$db->query('DELETE FROM misi_renstra_neo WHERE renstra_id=?',[$rid]);
  }$db->query('DELETE FROM renstra_neo WHERE kd_wilayah=? AND kd_opd=?',[$wilayah,$opd]);

  $ref=static function($db,string $code,string $parent,string $level,string $name)use($wilayah,$actor):int{$r=$db->query('SELECT id FROM rekening_kegiatan WHERE kode=? AND kd_wilayah=? LIMIT 1',[$code,$wilayah])->fetch();if($r){$db->update('rekening_kegiatan',['parent_kode'=>$parent,'level'=>$level,'uraian'=>$name,'status'=>1,'tgl_update'=>date('Y-m-d H:i:s'),'username_update'=>$actor],'WHERE id=?',[$r['id']]);return(int)$r['id'];}return(int)$db->insert('rekening_kegiatan',['kode'=>$code,'parent_kode'=>$parent,'level'=>$level,'uraian'=>$name,'kd_wilayah'=>$wilayah,'peraturan_id'=>4,'status'=>1,'tgl_insert'=>date('Y-m-d H:i:s'),'username_insert'=>$actor]);};
  $ref($db,'1','', 'urusan','URUSAN PEMERINTAHAN WAJIB YANG BERKAITAN DENGAN PELAYANAN DASAR');$ref($db,'1.03','1','bidang','URUSAN PEMERINTAHAN BIDANG PEKERJAAN UMUM DAN PENATAAN RUANG');
  foreach($programs as $x)$ref($db,$x['code'],'1.03','program',$clean($x['raw_name']));
  foreach($activities as $x){$parts=explode('.',$x['code']);$ref($db,$x['code'],implode('.',array_slice($parts,0,3)).'.2','kegiatan',$clean($x['raw_name']));}
  $master=[];foreach($subs as $x){$parts=explode('.',$x['code']);$parent=implode('.',array_slice($parts,0,5));$master[$x['code']]=$ref($db,$x['code'],$parent,'sub_kegiatan',$clean($x['raw_name']));}

  $renstra=$db->insert('renstra_neo',['kd_wilayah'=>$wilayah,'kd_opd'=>$opd,'periode_id'=>$period,'visi'=>'Penyediaan Infrastruktur Dasar Kabupaten Pasangkayu yang Berkualitas, Merata, Aman, dan Berkelanjutan','status'=>'aktif','kunci'=>0,'setujui'=>0,'disable'=>0,'keterangan'=>'Sumber: Renstra Dinas PUPR Kabupaten Pasangkayu, tabel pendanaan 2026-2030','username_insert'=>$actor,'is_deleted'=>0]);
  $misi=$db->insert('misi_renstra_neo',['renstra_id'=>$renstra,'nama_misi'=>'Meningkatkan kualitas, pemerataan, dan keberlanjutan layanan pekerjaan umum dan penataan ruang','keterangan'=>'Dirumuskan dari arah kebijakan dan program dalam dokumen sumber','username_insert'=>$actor,'is_deleted'=>0]);
  $tujuan=$db->insert('tujuan_renstra_neo',['misi_id'=>$misi,'kode_tujuan'=>'T.1','nama_tujuan'=>'Penyediaan Infrastruktur Dasar','username_insert'=>$actor,'is_deleted'=>0]);
  $sasaran=$db->insert('sasaran_renstra_neo',['tujuan_id'=>$tujuan,'kode_sasaran'=>'S.1','nama_sasaran'=>'Meningkatnya kualitas dan cakupan layanan infrastruktur dasar serta tata kelola PUPR','username_insert'=>$actor,'is_deleted'=>0]);
  $programIds=[];
  foreach($programs as $x){$detail=$x['detail']??[];$name=$clean($x['raw_name']);$programIds[$x['code']]=$db->insert('program_renstra_neo',['sasaran_id'=>$sasaran,'kode_program'=>$x['code'],'uraian'=>$name,'keterangan'=>$clean($detail['outcome']??''),'username_insert'=>$actor,'is_deleted'=>0]);$targets=$detail['targets']??[];$indicator=$clean($detail['indicator']??('Indikator '.$name));$satuan=$unit($indicator);$vals=['program_id'=>$programIds[$x['code']],'nama_indikator'=>$indicator,'satuan'=>$satuan,'baseline'=>$number($detail['baseline']??0),'target_t1'=>$number($targets[1]??0),'target_t2'=>$number($targets[2]??0),'target_t3'=>$number($targets[3]??0),'target_t4'=>$number($targets[4]??0),'target_t5'=>$number($targets[5]??0),'target_akhir'=>$number($targets[5]??0),'username_insert'=>$actor,'is_deleted'=>0];$db->insert('indikator_program_renstra_neo',$vals);}
  $ikuRows=[
    ['IKU-01','Indeks Infrastruktur','Angka',3.04,[3.86,4.27,4.68,5.09,5.50],null],
    ['IKU-02','Persentase tingkat kondisi jalan kabupaten/kota baik dan sedang','%',18.64,[23.65,26.16,28.65,31.15,33.65],'1.03.10'],
    ['IKU-03','Persentase Laporan yang disusun tepat waktu','%',88,[92,94,96,98,100],'1.03.01'],
    ['IKU-04','Persentase tersedianya luasan RTH publik sebesar 20% dari luas wilayah kota/kawasan','%',1.55,[0.31,0.31,0.31,0.31,0.31],'1.03.09'],
    ['IKU-05','Persentase Jumlah Penduduk yang terlayani air bersih','%',17,[3,4,4,4,4],'1.03.03'],
    ['IKU-06','Pengaturan NSPK (Norma, Standar, Prosedur, Kriteria) dalam kegiatan pengawasan','%',0,[100,100,100,100,100],'1.03.11'],
    ['IKU-07','Persentase Rumah Tinggal Bersanitasi','%',60.57,[64.57,66.57,68.57,70.57,72.57],'1.03.05']];
  foreach($ikuRows as [$code,$indicator,$satuan,$baseline,$targets,$programCode])$db->insert('iku_opd_neo',['kd_wilayah'=>$wilayah,'kd_opd'=>$opd,'renstra_id'=>$renstra,'sasaran_renstra_id'=>$sasaran,'program_renstra_id'=>$programCode?($programIds[$programCode]??null):null,'kode_iku'=>$code,'nama_indikator'=>$indicator,'definisi_operasional'=>'Indikator Kinerja Utama pada Tabel 4.5 Renstra Dinas PUPR Kabupaten Pasangkayu','satuan'=>$satuan,'polaritas'=>'maksimal','frekuensi_pengukuran'=>'tahunan','baseline'=>$baseline,'target_t1'=>$targets[0],'target_t2'=>$targets[1],'target_t3'=>$targets[2],'target_t4'=>$targets[3],'target_t5'=>$targets[4],'target_akhir'=>$targets[4],'status'=>'draft','keterangan'=>'Sumber Tabel 4.5 IKU Renstra 2025-2030','username_insert'=>$actor,'is_deleted'=>0]);
  $activityIds=[];foreach($activities as $x){$program=implode('.',array_slice(explode('.',$x['code']),0,3));$activityIds[$x['code']]=$db->insert('kegiatan_renstra_neo',['program_id'=>$programIds[$program],'kode_kegiatan'=>$x['code'],'uraian'=>$clean($x['raw_name']),'keterangan'=>$clean($x['detail']['outcome']??''),'username_insert'=>$actor,'is_deleted'=>0]);}
  foreach($subs as $x){$activity=implode('.',array_slice(explode('.',$x['code']),0,5));$d=$x['detail']??[];$targets=$d['targets']??[];$indicator=$clean($d['indicator']??'');$db->insert('sub_kegiatan_renstra_neo',['kegiatan_renstra_id'=>$activityIds[$activity],'master_sub_kegiatan_id'=>$master[$x['code']],'lokasi'=>$clean($x['row'][15]??'Kabupaten Pasangkayu')?:'Kabupaten Pasangkayu','kelompok_sasaran'=>'Masyarakat dan pemangku kepentingan Kabupaten Pasangkayu','indikator_keluaran'=>$indicator,'satuan'=>$unit($indicator),'baseline'=>$number($d['baseline']??0),'target_t1'=>$number($targets[1]??0),'anggaran_t1'=>$number($x['row'][5]??0),'target_t2'=>$number($targets[2]??0),'anggaran_t2'=>$number($x['row'][7]??0),'target_t3'=>$number($targets[3]??0),'anggaran_t3'=>$number($x['row'][9]??0),'target_t4'=>$number($targets[4]??0),'anggaran_t4'=>$number($x['row'][11]??0),'target_t5'=>$number($targets[5]??0),'anggaran_t5'=>$number($x['row'][13]??0),'target_akhir'=>$number($targets[5]??0),'keterangan'=>'Output: '.$clean($d['outcome']??''),'username_insert'=>$actor,'is_deleted'=>0]);}
  $db->query('DELETE FROM batas_pagu_opd_neo WHERE kd_wilayah=? AND kd_opd=? AND tahun BETWEEN 2025 AND 2030',[$wilayah,$opd]);
  foreach($totals as $year=>$total){foreach(['renja','rka','dpa','renja_p','rka_p','dppa'] as $doc)$db->insert('batas_pagu_opd_neo',['kd_wilayah'=>$wilayah,'kd_opd'=>$opd,'tahun'=>$year,'dokumen'=>$doc,'pagu_maksimal'=>$total,'keterangan'=>'Batas pagu TAPD berdasarkan pagu indikatif Renstra PUPR 2026-2030','username_insert'=>$actor,'is_deleted'=>0]);$existing=$db->query('SELECT id FROM master_biaya WHERE kode=? AND kd_wilayah=? AND tahun=? LIMIT 1',['PUPR-PAGU-'.$year,$wilayah,$year])->fetch();$ssh=['tipe'=>'ssh','kode'=>'PUPR-PAGU-'.$year,'kelompok_barang'=>'Komponen sementara penyusunan anggaran PUPR','uraian'=>'Komponen placeholder pagu Renstra PUPR '.$year,'spesifikasi'=>'Harga satuan sementara; wajib dirinci dan diganti OPD saat menyusun RKA/DPA','satuan_id'=>1,'harga'=>1,'keterangan'=>'DUMMY TERKENDALI - hanya untuk mengakomodasi input rincian sampai SSH definitif tersedia','kd_wilayah'=>$wilayah,'tahun'=>$year,'peraturan_id'=>4,'disable'=>0,'is_deleted'=>0,'username_insert'=>$actor];if($existing)$db->update('master_biaya',$ssh,'WHERE id=?',[$existing['id']]);else$db->insert('master_biaya',$ssh);}
  $db->commit();
  echo json_encode(['renstra_id'=>$renstra,'program'=>count($programs),'kegiatan'=>count($activities),'sub_kegiatan'=>count($subs),'iku'=>count($ikuRows),'pagu'=>$totals],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE),PHP_EOL;
}catch(Throwable $e){$db->rollback();throw $e;}
