<?php
require_once __DIR__.'/../Core/Auth.php';require_once __DIR__.'/../Core/DB.php';require_once __DIR__.'/../Services/JsonResponse.php';
class UserOpdController extends Controller
{
  private array $managers=['super_admin','admin_wilayah','admin_opd','kepala_opd'];
  private array $assignable=['pa_kpa','ppk','pptk','ppk_skpd','bendahara','pejabat_pengadaan','staf_opd','viewer'];
  private function guard():array{if(!Auth::check())throw new RuntimeException('Unauthorized');$u=$_SESSION['user'];if(!in_array($u['type_user']??'',$this->managers,true))throw new RuntimeException('Hanya kepala OPD atau administrator yang dapat mengatur user');return $u;}
  public function index(){try{$u=$this->guard();$this->view('pengaturan/user_opd',['roles'=>$this->assignable,'user'=>$u]);}catch(Throwable $e){http_response_code(403);echo htmlspecialchars($e->getMessage());}}
  public function list(){header('Content-Type: application/json;charset=UTF-8');try{$u=$this->guard();$sql='SELECT id,username,email,nama,nip,kd_opd,nama_org,kd_wilayah,type_user,tahun,kontak_person,disable FROM user_sesendok_biila WHERE kd_wilayah=?';$p=[$u['kd_wilayah']];if(($u['type_user']??'')!=='super_admin'&&($u['type_user']??'')!=='admin_wilayah'){$sql.=' AND kd_opd=?';$p[]=$u['kd_opd'];}$sql.=' AND type_user IN ('.implode(',',array_fill(0,count($this->assignable),'?')).') ORDER BY nama';array_push($p,...$this->assignable);echo JsonResponse::success('Daftar user OPD',[],DB::getInstance()->query($sql,$p)->fetchAll());}catch(Throwable $e){echo JsonResponse::error($e->getMessage(),403);}}
  public function save(){header('Content-Type: application/json;charset=UTF-8');try{$u=$this->guard();$id=(int)($_POST['id']??0);$role=(string)($_POST['type_user']??'');if(!in_array($role,$this->assignable,true))throw new InvalidArgumentException('Role tidak boleh ditetapkan oleh pengelola OPD');$required=['username','email','nama'];foreach($required as $f)if(trim((string)($_POST[$f]??''))==='')throw new InvalidArgumentException(ucwords($f).' wajib diisi');$db=DB::getInstance();$data=['username'=>trim($_POST['username']),'email'=>trim($_POST['email']),'nama'=>trim($_POST['nama']),'nip'=>trim((string)($_POST['nip']??''))?:null,'type_user'=>$role,'kontak_person'=>trim((string)($_POST['kontak_person']??'')),'kd_wilayah'=>$u['kd_wilayah'],'kd_opd'=>$u['kd_opd'],'nama_org'=>$u['nama_org']??'OPD','tahun'=>$u['tahun'],'disable'=>!empty($_POST['disable'])?1:0,'disable_login'=>!empty($_POST['disable'])?1:0];$password=(string)($_POST['password']??'');if(!$id&&strlen($password)<8)throw new InvalidArgumentException('Password awal minimal 8 karakter');if($password!=='')$data['password']=password_hash($password,PASSWORD_DEFAULT);$duplicate=$db->query('SELECT id FROM user_sesendok_biila WHERE (username=? OR email=?) AND id<>? LIMIT 1',[$data['username'],$data['email'],$id])->fetch();if($duplicate)throw new InvalidArgumentException('Username atau email sudah digunakan');if($id){$target=$db->query('SELECT id,kd_wilayah,kd_opd,type_user FROM user_sesendok_biila WHERE id=?',[$id])->fetch();if(!$target||(!$this->canTouch($u,$target)))throw new RuntimeException('User bukan dalam lingkup pengelola');$db->update('user_sesendok_biila',$data,'WHERE id=?',[$id]);}else{$data['tgl_daftar']=date('Y-m-d H:i:s');$data['photo']='default.jpeg';$id=$db->insert('user_sesendok_biila',$data);}echo JsonResponse::success('User OPD berhasil disimpan',['id'=>$id]);}catch(Throwable $e){echo JsonResponse::error($e->getMessage(),400);}}
  public function delete(){header('Content-Type: application/json;charset=UTF-8');try{$u=$this->guard();$id=(int)($_POST['id']??0);$db=DB::getInstance();$target=$db->query('SELECT id,kd_wilayah,kd_opd,type_user FROM user_sesendok_biila WHERE id=?',[$id])->fetch();if(!$target||!$this->canTouch($u,$target))throw new RuntimeException('User bukan dalam lingkup pengelola');$db->update('user_sesendok_biila',['disable'=>1,'disable_login'=>1],'WHERE id=?',[$id]);$db->query('UPDATE user_subkegiatan_neo SET is_deleted=1 WHERE user_id=?',[$id]);echo JsonResponse::success('User dinonaktifkan dan penugasannya dicabut');}catch(Throwable $e){echo JsonResponse::error($e->getMessage(),403);}}
  private function canTouch(array $u,array $target):bool{if(!in_array($target['type_user'],$this->assignable,true))return false;if(($u['type_user']??'')==='super_admin')return true;if($target['kd_wilayah']!==($u['kd_wilayah']??null))return false;if(($u['type_user']??'')==='admin_wilayah')return true;return $target['kd_opd']===($u['kd_opd']??null);}
}
