<div class="ui container monthly-account-page" data-table="<?= htmlspecialchars($table) ?>" data-sub="<?= htmlspecialchars($subCode) ?>">
  <div class="ui clearing segment">
    <a class="ui left floated basic button" href="<?= app_url('/'.($table==='dppa'?'dppa':'dpa')) ?>" data-spa="server"><i class="arrow left icon"></i>Kembali ke Uraian Sub Kegiatan</a>
    <h2 class="ui right floated header"><i class="calendar alternate teal icon"></i><div class="content">Rencana Penarikan per Rekening<div class="sub header"><?= htmlspecialchars(strtoupper($table).' - '.$subCode) ?></div></div></h2>
  </div>
  <div class="ui blue message">Pembagian dilakukan pada kode rekening belanja level akhir. Total Januari-Desember tidak boleh melebihi pagu rekening. Sistem merangkum seluruh rekening menjadi rencana bulanan per sub kegiatan.</div>
  <div class="monthly-account-scroll"><table class="ui celled striped table" style="min-width:1500px"><thead><tr><th>Kode Rekening</th><th>Uraian Rekening</th><th>Pagu</th><th>Total Rencana</th><th>Sisa</th><th>Aksi</th></tr></thead><tbody id="monthlyAccountRows"><tr><td colspan="6"><div class="ui active centered inline loader"></div></td></tr></tbody></table></div>
</div>
<style>.monthly-account-scroll{overflow-x:auto;-webkit-overflow-scrolling:touch}.monthly-editor td{background:#f7fbff!important}.monthly-grid{display:grid;grid-template-columns:repeat(6,minmax(150px,1fr));gap:10px}.monthly-grid .field label{display:block;font-weight:700;margin-bottom:4px}@media(max-width:800px){.monthly-grid{grid-template-columns:repeat(2,minmax(150px,1fr))}}</style>
<script>$(function(){const root=$('.monthly-account-page'),tbl=root.data('table'),sub=root.data('sub'),months=['Januari','Februari','Maret','April','Mei','Juni','Juli','Agustus','September','Oktober','November','Desember'],money=v=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(v||0)),esc=v=>$('<div>').text(v??'').html();let records=[];const load=()=>window.Ajax.request({url:`/anggaran/rencana-rekening/data?tbl=${encodeURIComponent(tbl)}&kd_sub_keg=${encodeURIComponent(sub)}`,method:'GET',success:r=>{records=r.data||[];$('#monthlyAccountRows').html(records.map((x,i)=>`<tr><td><b>${esc(x.kd_akun)}</b></td><td>${esc(x.uraian)}</td><td class="right aligned">${money(x.pagu)}</td><td class="right aligned"><b>${money(x.total_rencana)}</b></td><td class="right aligned ${Number(x.sisa)<0?'negative':''}">${money(x.sisa)}</td><td><button class="ui mini teal button editMonthlyAccount" data-index="${i}"><i class="calendar icon"></i>Atur Bulanan</button></td></tr>`).join('')||'<tr><td colspan="6">Belum ada rekening belanja level akhir.</td></tr>')}});$(document).on('click','.editMonthlyAccount',function(){const i=Number($(this).data('index')),x=records[i],row=$(this).closest('tr');$('.monthly-editor').remove();row.after(`<tr class="monthly-editor"><td colspan="6"><form class="ui form account-month-form" data-account="${esc(x.kd_akun)}"><div class="monthly-grid">${months.map((m,n)=>`<div class="field"><label>${m}</label><input type="number" min="0" step="0.01" name="m${n+1}" value="${Number(x.months?.[n+1]||0)}"></div>`).join('')}</div><div class="ui divider"></div><span class="ui label">Pagu ${money(x.pagu)}</span><span class="ui teal label monthlyCalculated">Total ${money(x.total_rencana)}</span><button class="ui right floated primary button" type="submit"><i class="save icon"></i>Simpan Rekening</button><button class="ui right floated basic button closeMonthlyEditor" type="button">Tutup</button></form></td></tr>`)});$(document).on('input','.account-month-form input',function(){let total=0;$(this).closest('form').find('input').each(function(){total+=Number(this.value||0)});$(this).closest('form').find('.monthlyCalculated').text('Total '+money(total))});$(document).on('click','.closeMonthlyEditor',()=>$('.monthly-editor').remove());$(document).on('submit','.account-month-form',function(e){e.preventDefault();const values={};for(let i=1;i<=12;i++)values[i]=Number($(this).find(`[name=m${i}]`).val()||0);window.Ajax.request({url:'/anggaran/rencana-rekening/data',method:'POST',data:{tbl,kd_sub_keg:sub,kd_akun:$(this).data('account'),jenis:'belanja',months:JSON.stringify(values)},success:()=>{Toast.success('Rencana rekening bulanan tersimpan');load()}})});load();});</script>
